//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANBO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANBO()
        {
            this.KHENTHUONGs = new HashSet<KHENTHUONG>();
            this.KYLUATs = new HashSet<KYLUAT>();
            this.THOIKHOABIEUs = new HashSet<THOIKHOABIEU>();
            this.THONGTINDAOTAOs = new HashSet<THONGTINDAOTAO>();
            this.THONGTINLUONGs = new HashSet<THONGTINLUONG>();
        }
    
        public string CB_MA { get; set; }
        public string CB_HOTEN { get; set; }
        public string CB_GIOITINH { get; set; }
        public string CB_DIACHI { get; set; }
        public Nullable<System.DateTime> CB_NGAYSINH { get; set; }
        public string CB_CMND { get; set; }
        public string CQ_MA { get; set; }
        public string CV_MA { get; set; }
        public string Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHENTHUONG> KHENTHUONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KYLUAT> KYLUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUs { get; set; }
        public virtual COQUAN COQUAN { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINDAOTAO> THONGTINDAOTAOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINLUONG> THONGTINLUONGs { get; set; }
    }
}
