//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public string LOP_MA { get; set; }
        public string LOP_TEN { get; set; }
        public string KHOI_MA { get; set; }
        public string NH_MA { get; set; }
    
        public virtual KHOIs KHOIs { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
