//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANBO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANBO()
        {
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
        }
    
        public string CB_MA { get; set; }
        public string CB_HOTEN { get; set; }
        public string CB_GIOITINH { get; set; }
        public string CB_DIACHI { get; set; }
        public Nullable<System.DateTime> CB_NGAYSINH { get; set; }
        public string CB_CMND { get; set; }
        public string COQUAN_CQ_MA { get; set; }
        public System.TimeSpan CHITIET_CHUCVU_CT_CV_ID { get; set; }
        public string KYLUATCB_KLCB_MA { get; set; }
        public string KHENTHUONGCB_KTCB_MA { get; set; }
        public string THONGTINDAOTAO_TTDT_MA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        public virtual CHITIET_CHUCVU CHITIET_CHUCVU { get; set; }
        public virtual COQUAN COQUAN { get; set; }
        public virtual KHENTHUONGCB KHENTHUONGCB { get; set; }
        public virtual KYLUATCB KYLUATCB { get; set; }
        public virtual THONGTINDAOTAO THONGTINDAOTAO { get; set; }
    }
}
