//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_CHUCVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIET_CHUCVU()
        {
            this.CANBOes = new HashSet<CANBO>();
        }
    
        public System.TimeSpan CT_CV_ID { get; set; }
        public string CT_CV_TEN { get; set; }
        public string CHUCVU_CV_MA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANBO> CANBOes { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
    }
}
