//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDANHGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETDANHGIA()
        {
            this.HOCSINHs = new HashSet<HOCSINH>();
        }
    
        public string CTDG_MA { get; set; }
        public Nullable<System.DateTime> CTDG_NGAYDG { get; set; }
        public string SODANHGIA_SDG_MA { get; set; }
        public string MONHOC_MH_MA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCSINH> HOCSINHs { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual SODANHGIA SODANHGIA { get; set; }
    }
}
