//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDANHGIA
    {
        public string CTDG_MA { get; set; }
        public Nullable<System.DateTime> CTDG_NGAYDG { get; set; }
        public string SDG_MA { get; set; }
        public string HS_MA { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual SODANHGIA SODANHGIA { get; set; }
    }
}
