//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCKy
    {
        public HOCKy()
        {
            this.SODANHGIAs = new HashSet<SODANHGIA>();
        }
    
        public string HK_MA { get; set; }
        public string HK_TEN { get; set; }
    
        public virtual ICollection<SODANHGIA> SODANHGIAs { get; set; }
    }
}
