//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCSINH()
        {
            this.KYLUATs = new HashSet<KYLUAT>();
            this.CHITIETDANHGIAs = new HashSet<CHITIETDANHGIA>();
            this.KHENTHUONGs = new HashSet<KHENTHUONG>();
        }
    
        public string HS_MA { get; set; }
        public string HS_HOTEN { get; set; }
        public string HS_GIOITINH { get; set; }
        public System.DateTime HS_NGAYSINH { get; set; }
        public string HS_TONGIAO { get; set; }
    
        public virtual TINHTHANH TINHTHANH { get; set; }
        public virtual XAPHUONG XAPHUONG { get; set; }
        public virtual QUANHUYEN QUANHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KYLUAT> KYLUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDANHGIA> CHITIETDANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHENTHUONG> KHENTHUONGs { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual DANTOC DANTOC { get; set; }
    }
}
