//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        public HOCSINH()
        {
            this.KHENTHUONGs = new HashSet<KHENTHUONG>();
            this.KYLUATs = new HashSet<KYLUAT>();
        }
    
        public string HS_MA { get; set; }
        public string HS_HOTEN { get; set; }
        public string HS_GIOITINH { get; set; }
        public System.DateTime HS_NGAYSINH { get; set; }
        public string HS_TONGIAO { get; set; }
        public string TT_MA { get; set; }
        public string QH_MA { get; set; }
        public string XP_MA { get; set; }
        public string DT_MA { get; set; }
        public string SODANHGIAs_SDG_MA { get; set; }
    
        public virtual ICollection<KHENTHUONG> KHENTHUONGs { get; set; }
        public virtual ICollection<KYLUAT> KYLUATs { get; set; }
        public virtual DANTOC DANTOC { get; set; }
        public virtual QUANHUYEN QUANHUYEN { get; set; }
        public virtual TINHTHANH TINHTHANH { get; set; }
        public virtual XAPHUONG XAPHUONG { get; set; }
        public virtual SODANHGIA SODANHGIA { get; set; }
    }
}
