//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYLUATCB
    {
        public string KLCB_MA { get; set; }
        public string KLCB_NGAY { get; set; }
        public string KLCB_HT { get; set; }
    
        public virtual CANBO CANBO { get; set; }
    }
}
