//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYLUAT
    {
        public string KL_MA { get; set; }
        public string KL_HINHTHUC { get; set; }
        public Nullable<System.DateTime> KL_NGAYKYLUAT { get; set; }
        public string CB_MA { get; set; }
        public string HS_MA { get; set; }
    
        public virtual CANBO CANBO { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
