//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class acomptec_qlthptEntities3 : DbContext
    {
        public acomptec_qlthptEntities3()
            : base("name=acomptec_qlthptEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDANHGIA> CHITIETDANHGIAs { get; set; }
        public virtual DbSet<KHENTHUONG> KHENTHUONGs { get; set; }
        public virtual DbSet<KHOIs> KHOIs { get; set; }
        public virtual DbSet<KYLUAT> KYLUATs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<NAMHOC> NAMHOCs { get; set; }
        public virtual DbSet<THOIKHOABIEU> THOIKHOABIEUs { get; set; }
        public virtual DbSet<UpdateImage> UpdateImages { get; set; }
        public virtual DbSet<BACLUONG> BACLUONGs { get; set; }
        public virtual DbSet<CANBO> CANBOes { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CHUYENNGANH> CHUYENNGANHs { get; set; }
        public virtual DbSet<COQUAN> COQUANs { get; set; }
        public virtual DbSet<COSOVATCHAT> COSOVATCHATs { get; set; }
        public virtual DbSet<DANTOC> DANTOCs { get; set; }
        public virtual DbSet<HINHTHUC> HINHTHUCs { get; set; }
        public virtual DbSet<HOCKy> HOCKies { get; set; }
        public virtual DbSet<HOCSINH> HOCSINHs { get; set; }
        public virtual DbSet<MONHOC> MONHOCs { get; set; }
        public virtual DbSet<NGACHLUONG> NGACHLUONGs { get; set; }
        public virtual DbSet<PHONGHOC> PHONGHOCs { get; set; }
        public virtual DbSet<QUANHUYEN> QUANHUYENs { get; set; }
        public virtual DbSet<SODANHGIA> SODANHGIAs { get; set; }
        public virtual DbSet<THIETBIDAYHOC> THIETBIDAYHOCs { get; set; }
        public virtual DbSet<THIETBIGIANGDAY> THIETBIGIANGDAYs { get; set; }
        public virtual DbSet<THONGTINDAOTAO> THONGTINDAOTAOs { get; set; }
        public virtual DbSet<THONGTINLUONG> THONGTINLUONGs { get; set; }
        public virtual DbSet<THU> THUs { get; set; }
        public virtual DbSet<TIETHOC> TIETHOCs { get; set; }
        public virtual DbSet<TINHTHANH> TINHTHANHs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
        public virtual DbSet<VANBANG> VANBANGs { get; set; }
        public virtual DbSet<XAPHUONG> XAPHUONGs { get; set; }
        public virtual DbSet<CHITIET_CHUCVU> CHITIET_CHUCVU { get; set; }
    }
}
