
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 04/03/2020 12:48:52
-- Generated from EDMX file: C:\Users\OS\Documents\QLTHPT\QLTHPT\Models\ModelDB.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [acomptec_qlthpt];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_BACLUONGTHONGTINLUONG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINLUONGs] DROP CONSTRAINT [FK_BACLUONGTHONGTINLUONG];
GO
IF OBJECT_ID(N'[dbo].[FK_CANBOCHITIET_CHUCVU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHITIET_CHUCVU] DROP CONSTRAINT [FK_CANBOCHITIET_CHUCVU];
GO
IF OBJECT_ID(N'[dbo].[FK_CANBOTHONGTINDAOTAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINDAOTAOs] DROP CONSTRAINT [FK_CANBOTHONGTINDAOTAO];
GO
IF OBJECT_ID(N'[dbo].[FK_CANBOTHONGTINLUONG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBOes] DROP CONSTRAINT [FK_CANBOTHONGTINLUONG];
GO
IF OBJECT_ID(N'[dbo].[FK_COQUANCANBO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBOes] DROP CONSTRAINT [FK_COQUANCANBO];
GO
IF OBJECT_ID(N'[dbo].[FK_CHUCVUCHITIET_CHUCVU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHITIET_CHUCVU] DROP CONSTRAINT [FK_CHUCVUCHITIET_CHUCVU];
GO
IF OBJECT_ID(N'[dbo].[FK_HOCSINHCHITIETDANHGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHITIETDANHGIAs] DROP CONSTRAINT [FK_HOCSINHCHITIETDANHGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_SODANHGIACHITIETDANHGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHITIETDANHGIAs] DROP CONSTRAINT [FK_SODANHGIACHITIETDANHGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_THONGTINDAOTAOCHUYENNGANH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHUYENNGANHs] DROP CONSTRAINT [FK_THONGTINDAOTAOCHUYENNGANH];
GO
IF OBJECT_ID(N'[dbo].[FK_COSOVATCHATTHIETBIDAYHOC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THIETBIDAYHOCs] DROP CONSTRAINT [FK_COSOVATCHATTHIETBIDAYHOC];
GO
IF OBJECT_ID(N'[dbo].[FK_COSOVATCHATTHIETBIGIANGDAY]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THIETBIGIANGDAYs] DROP CONSTRAINT [FK_COSOVATCHATTHIETBIGIANGDAY];
GO
IF OBJECT_ID(N'[dbo].[FK_COSOVATCHATTINHTRANG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TINHTRANGs] DROP CONSTRAINT [FK_COSOVATCHATTINHTRANG];
GO
IF OBJECT_ID(N'[dbo].[FK_PHONGHOCCOSOVATCHAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COSOVATCHATs] DROP CONSTRAINT [FK_PHONGHOCCOSOVATCHAT];
GO
IF OBJECT_ID(N'[dbo].[FK_DANTOCHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINHs] DROP CONSTRAINT [FK_DANTOCHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_THONGTINDAOTAOHINHTHUC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINDAOTAOs] DROP CONSTRAINT [FK_THONGTINDAOTAOHINHTHUC];
GO
IF OBJECT_ID(N'[dbo].[FK_HOCKySODANHGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SODANHGIAs] DROP CONSTRAINT [FK_HOCKySODANHGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_HOCSINHKHENTHUONG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[KHENTHUONGs] DROP CONSTRAINT [FK_HOCSINHKHENTHUONG];
GO
IF OBJECT_ID(N'[dbo].[FK_HOCSINHKYLUAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[KYLUATs] DROP CONSTRAINT [FK_HOCSINHKYLUAT];
GO
IF OBJECT_ID(N'[dbo].[FK_LOPHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINHs] DROP CONSTRAINT [FK_LOPHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_QUANHUYENHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINHs] DROP CONSTRAINT [FK_QUANHUYENHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_TINHTHANHHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINHs] DROP CONSTRAINT [FK_TINHTHANHHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_XAPHUONGHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINHs] DROP CONSTRAINT [FK_XAPHUONGHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_KHOIsLOP]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LOPs] DROP CONSTRAINT [FK_KHOIsLOP];
GO
IF OBJECT_ID(N'[dbo].[FK_LOPTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEUs] DROP CONSTRAINT [FK_LOPTHOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[FK_NAMHOCLOP]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LOPs] DROP CONSTRAINT [FK_NAMHOCLOP];
GO
IF OBJECT_ID(N'[dbo].[FK_THOIKHOABIEUMONHOC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MONHOCs] DROP CONSTRAINT [FK_THOIKHOABIEUMONHOC];
GO
IF OBJECT_ID(N'[dbo].[FK_NGACHLUONGTHONGTINLUONG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINLUONGs] DROP CONSTRAINT [FK_NGACHLUONGTHONGTINLUONG];
GO
IF OBJECT_ID(N'[dbo].[FK_THOIKHOABIEUTHU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THUs] DROP CONSTRAINT [FK_THOIKHOABIEUTHU];
GO
IF OBJECT_ID(N'[dbo].[FK_THOIKHOABIEUTIETHOC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TIETHOCs] DROP CONSTRAINT [FK_THOIKHOABIEUTIETHOC];
GO
IF OBJECT_ID(N'[dbo].[FK_THONGTINDAOTAOVANBANG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[VANBANGs] DROP CONSTRAINT [FK_THONGTINDAOTAOVANBANG];
GO
IF OBJECT_ID(N'[dbo].[FK_CANBOKHENTHUONGCB]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[KHENTHUONGCBs] DROP CONSTRAINT [FK_CANBOKHENTHUONGCB];
GO
IF OBJECT_ID(N'[dbo].[FK_CANBOKYLUATCB]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[KYLUATCBs] DROP CONSTRAINT [FK_CANBOKYLUATCB];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[BACLUONGs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BACLUONGs];
GO
IF OBJECT_ID(N'[dbo].[CANBOes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CANBOes];
GO
IF OBJECT_ID(N'[dbo].[CHITIET_CHUCVU]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHITIET_CHUCVU];
GO
IF OBJECT_ID(N'[dbo].[CHITIETDANHGIAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHITIETDANHGIAs];
GO
IF OBJECT_ID(N'[dbo].[CHUCVUs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHUCVUs];
GO
IF OBJECT_ID(N'[dbo].[CHUYENNGANHs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHUYENNGANHs];
GO
IF OBJECT_ID(N'[dbo].[COQUANs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[COQUANs];
GO
IF OBJECT_ID(N'[dbo].[COSOVATCHATs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[COSOVATCHATs];
GO
IF OBJECT_ID(N'[dbo].[DANTOCs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DANTOCs];
GO
IF OBJECT_ID(N'[dbo].[HINHTHUCs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[HINHTHUCs];
GO
IF OBJECT_ID(N'[dbo].[HOCKies]', 'U') IS NOT NULL
    DROP TABLE [dbo].[HOCKies];
GO
IF OBJECT_ID(N'[dbo].[HOCSINHs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[HOCSINHs];
GO
IF OBJECT_ID(N'[dbo].[KHENTHUONGs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KHENTHUONGs];
GO
IF OBJECT_ID(N'[dbo].[KHOIs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KHOIs];
GO
IF OBJECT_ID(N'[dbo].[KYLUATs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KYLUATs];
GO
IF OBJECT_ID(N'[dbo].[LOPs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LOPs];
GO
IF OBJECT_ID(N'[dbo].[MONHOCs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MONHOCs];
GO
IF OBJECT_ID(N'[dbo].[NAMHOCs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[NAMHOCs];
GO
IF OBJECT_ID(N'[dbo].[NGACHLUONGs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[NGACHLUONGs];
GO
IF OBJECT_ID(N'[dbo].[PHONGHOCs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PHONGHOCs];
GO
IF OBJECT_ID(N'[dbo].[QUANHUYENs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[QUANHUYENs];
GO
IF OBJECT_ID(N'[dbo].[SODANHGIAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SODANHGIAs];
GO
IF OBJECT_ID(N'[dbo].[THIETBIDAYHOCs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THIETBIDAYHOCs];
GO
IF OBJECT_ID(N'[dbo].[THIETBIGIANGDAYs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THIETBIGIANGDAYs];
GO
IF OBJECT_ID(N'[dbo].[THOIKHOABIEUs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THOIKHOABIEUs];
GO
IF OBJECT_ID(N'[dbo].[THONGTINDAOTAOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THONGTINDAOTAOs];
GO
IF OBJECT_ID(N'[dbo].[THONGTINLUONGs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THONGTINLUONGs];
GO
IF OBJECT_ID(N'[dbo].[THUs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THUs];
GO
IF OBJECT_ID(N'[dbo].[TIETHOCs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIETHOCs];
GO
IF OBJECT_ID(N'[dbo].[TINHTHANHs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TINHTHANHs];
GO
IF OBJECT_ID(N'[dbo].[TINHTRANGs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TINHTRANGs];
GO
IF OBJECT_ID(N'[dbo].[UpdateImages]', 'U') IS NOT NULL
    DROP TABLE [dbo].[UpdateImages];
GO
IF OBJECT_ID(N'[dbo].[VANBANGs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[VANBANGs];
GO
IF OBJECT_ID(N'[dbo].[XAPHUONGs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[XAPHUONGs];
GO
IF OBJECT_ID(N'[dbo].[KHENTHUONGCBs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KHENTHUONGCBs];
GO
IF OBJECT_ID(N'[dbo].[KYLUATCBs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KYLUATCBs];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'BACLUONGs'
CREATE TABLE [dbo].[BACLUONGs] (
    [BL_MA] varchar(10)  NOT NULL,
    [BL_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'CANBOes'
CREATE TABLE [dbo].[CANBOes] (
    [CB_MA] varchar(10)  NOT NULL,
    [CB_HOTEN] nvarchar(50)  NOT NULL,
    [CB_GIOITINH] varchar(10)  NULL,
    [CB_DIACHI] nvarchar(200)  NULL,
    [CB_NGAYSINH] datetime  NULL,
    [CB_CMND] varchar(20)  NOT NULL,
    [THONGTINLUONGs_TTL_MA] varchar(10)  NOT NULL,
    [COQUAN_CQ_MA] varchar(10)  NOT NULL,
    [KHENTHUONGCB_KTCB_MA] nvarchar(max)  NOT NULL,
    [KYLUATCB_KLCB_MA] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'CHITIET_CHUCVU'
CREATE TABLE [dbo].[CHITIET_CHUCVU] (
    [CT_CV_ID] time  NOT NULL,
    [CT_CV_TEN] nvarchar(max)  NOT NULL,
    [CANBO_CB_MA] varchar(10)  NOT NULL,
    [CHUCVU_CV_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'CHITIETDANHGIAs'
CREATE TABLE [dbo].[CHITIETDANHGIAs] (
    [CTDG_MA] varchar(10)  NOT NULL,
    [CTDG_NGAYDG] datetime  NULL,
    [HOCSINH_HS_MA] varchar(10)  NOT NULL,
    [SODANHGIA_SDG_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'CHUCVUs'
CREATE TABLE [dbo].[CHUCVUs] (
    [CV_MA] varchar(10)  NOT NULL,
    [CV_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'CHUYENNGANHs'
CREATE TABLE [dbo].[CHUYENNGANHs] (
    [CN_MA] varchar(10)  NOT NULL,
    [CN_TEN] nvarchar(50)  NULL,
    [THONGTINDAOTAO_TTDT_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'COQUANs'
CREATE TABLE [dbo].[COQUANs] (
    [CQ_MA] varchar(10)  NOT NULL,
    [CQ_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'COSOVATCHATs'
CREATE TABLE [dbo].[COSOVATCHATs] (
    [CSVC_MA] varchar(10)  NOT NULL,
    [CSVC_SOLUONG] int  NOT NULL,
    [PHONGHOC_PH_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'DANTOCs'
CREATE TABLE [dbo].[DANTOCs] (
    [DT_MA] varchar(10)  NOT NULL,
    [DT_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'HINHTHUCs'
CREATE TABLE [dbo].[HINHTHUCs] (
    [HT_MA] varchar(10)  NOT NULL,
    [HT_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'HOCKies'
CREATE TABLE [dbo].[HOCKies] (
    [HK_MA] varchar(10)  NOT NULL,
    [HK_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'HOCSINHs'
CREATE TABLE [dbo].[HOCSINHs] (
    [HS_MA] varchar(10)  NOT NULL,
    [HS_HOTEN] nvarchar(50)  NOT NULL,
    [HS_GIOITINH] varchar(10)  NULL,
    [HS_NGAYSINH] datetime  NOT NULL,
    [HS_TONGIAO] nvarchar(20)  NULL,
    [TINHTHANH_TT_MA] varchar(10)  NOT NULL,
    [XAPHUONG_XP_MA] varchar(10)  NOT NULL,
    [QUANHUYEN_QH_MA] varchar(10)  NOT NULL,
    [LOP_LOP_MA] varchar(10)  NOT NULL,
    [DANTOC_DT_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'KHENTHUONGs'
CREATE TABLE [dbo].[KHENTHUONGs] (
    [KT_MA] varchar(10)  NOT NULL,
    [KT_THANHTICH] nvarchar(50)  NULL,
    [KT_NGAYKHENTHUONG] datetime  NULL,
    [KT_GHICHU] nvarchar(100)  NULL,
    [HOCSINH_HS_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'KHOIs'
CREATE TABLE [dbo].[KHOIs] (
    [KHOI_MA] varchar(10)  NOT NULL,
    [KHOI_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'KYLUATs'
CREATE TABLE [dbo].[KYLUATs] (
    [KL_MA] varchar(10)  NOT NULL,
    [KL_HINHTHUC] nvarchar(50)  NULL,
    [KL_NGAYKYLUAT] datetime  NULL,
    [HOCSINH_HS_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'LOPs'
CREATE TABLE [dbo].[LOPs] (
    [LOP_MA] varchar(10)  NOT NULL,
    [LOP_TEN] nvarchar(50)  NULL,
    [KHOIs_KHOI_MA] varchar(10)  NOT NULL,
    [NAMHOC_NH_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'MONHOCs'
CREATE TABLE [dbo].[MONHOCs] (
    [MH_MA] varchar(10)  NOT NULL,
    [MH_TEN] nvarchar(50)  NULL,
    [THOIKHOABIEU_TKB_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'NAMHOCs'
CREATE TABLE [dbo].[NAMHOCs] (
    [NH_MA] varchar(10)  NOT NULL,
    [NH_NAMHOC] nvarchar(50)  NULL
);
GO

-- Creating table 'NGACHLUONGs'
CREATE TABLE [dbo].[NGACHLUONGs] (
    [NL_MA] varchar(10)  NOT NULL,
    [NL_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'PHONGHOCs'
CREATE TABLE [dbo].[PHONGHOCs] (
    [PH_MA] varchar(10)  NOT NULL,
    [PH_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'QUANHUYENs'
CREATE TABLE [dbo].[QUANHUYENs] (
    [QH_MA] varchar(10)  NOT NULL,
    [QH_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'SODANHGIAs'
CREATE TABLE [dbo].[SODANHGIAs] (
    [SDG_MA] varchar(10)  NOT NULL,
    [SDG_DIEM] varchar(10)  NULL,
    [SDG_GHICHU] nvarchar(50)  NULL,
    [HOCKy_HK_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THIETBIDAYHOCs'
CREATE TABLE [dbo].[THIETBIDAYHOCs] (
    [TBDH_MA] varchar(10)  NOT NULL,
    [TBDH_TEN] nvarchar(50)  NOT NULL,
    [COSOVATCHAT_CSVC_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THIETBIGIANGDAYs'
CREATE TABLE [dbo].[THIETBIGIANGDAYs] (
    [TBGD_MA] varchar(10)  NOT NULL,
    [TBGD_TEN] nvarchar(50)  NOT NULL,
    [COSOVATCHAT_CSVC_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THOIKHOABIEUs'
CREATE TABLE [dbo].[THOIKHOABIEUs] (
    [TKB_MA] varchar(10)  NOT NULL,
    [LOP_LOP_MA] varchar(10)  NOT NULL,
    [CANBO_CB_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THONGTINDAOTAOs'
CREATE TABLE [dbo].[THONGTINDAOTAOs] (
    [TTDT_MA] varchar(10)  NOT NULL,
    [CANBO_CB_MA] varchar(10)  NOT NULL,
    [HINHTHUCs_HT_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THONGTINLUONGs'
CREATE TABLE [dbo].[THONGTINLUONGs] (
    [TTL_MA] varchar(10)  NOT NULL,
    [TTL_NGAYNHANLUONG] nvarchar(50)  NULL,
    [TTL_HESOLUONG] varchar(10)  NULL,
    [BACLUONG_BL_MA] varchar(10)  NOT NULL,
    [NGACHLUONG_NL_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THUs'
CREATE TABLE [dbo].[THUs] (
    [THU_MA] varchar(10)  NOT NULL,
    [THU_TEN] nvarchar(50)  NOT NULL,
    [THOIKHOABIEU_TKB_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'TIETHOCs'
CREATE TABLE [dbo].[TIETHOCs] (
    [TH_MA] varchar(10)  NOT NULL,
    [TH_TEN] nvarchar(50)  NOT NULL,
    [THOIKHOABIEU_TKB_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'TINHTHANHs'
CREATE TABLE [dbo].[TINHTHANHs] (
    [TT_MA] varchar(10)  NOT NULL,
    [TT_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'TINHTRANGs'
CREATE TABLE [dbo].[TINHTRANGs] (
    [TT_MA] varchar(10)  NOT NULL,
    [TT_MOTA] nvarchar(200)  NULL,
    [COSOVATCHAT_CSVC_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'UpdateImages'
CREATE TABLE [dbo].[UpdateImages] (
    [Id] varchar(50)  NOT NULL,
    [Image_url] nvarchar(100)  NULL,
    [Name_im] nvarchar(100)  NULL
);
GO

-- Creating table 'VANBANGs'
CREATE TABLE [dbo].[VANBANGs] (
    [VB_MA] varchar(10)  NOT NULL,
    [VB_TEN] nvarchar(50)  NULL,
    [THONGTINDAOTAO_TTDT_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'XAPHUONGs'
CREATE TABLE [dbo].[XAPHUONGs] (
    [XP_MA] varchar(10)  NOT NULL,
    [XP_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'KHENTHUONGCBs'
CREATE TABLE [dbo].[KHENTHUONGCBs] (
    [KTCB_MA] int IDENTITY(1,1) NOT NULL,
    [KTCB_NGAY] nvarchar(max)  NOT NULL,
    [KTCB_THANHTICH] nvarchar(max)  NOT NULL,
    [CANBO_CB_MA] nvarchar(max)  NOT NULL,
    [CANBOes_CB_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'KYLUATCBs'
CREATE TABLE [dbo].[KYLUATCBs] (
    [KLCB_MA] int IDENTITY(1,1) NOT NULL,
    [KLCB_NGAY] nvarchar(max)  NOT NULL,
    [KLCB_HINHTHUC] nvarchar(max)  NOT NULL,
    [CANBO_CB_MA] nvarchar(max)  NOT NULL,
    [CANBOes_CB_MA] varchar(10)  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [BL_MA] in table 'BACLUONGs'
ALTER TABLE [dbo].[BACLUONGs]
ADD CONSTRAINT [PK_BACLUONGs]
    PRIMARY KEY CLUSTERED ([BL_MA] ASC);
GO

-- Creating primary key on [CB_MA] in table 'CANBOes'
ALTER TABLE [dbo].[CANBOes]
ADD CONSTRAINT [PK_CANBOes]
    PRIMARY KEY CLUSTERED ([CB_MA] ASC);
GO

-- Creating primary key on [CT_CV_ID] in table 'CHITIET_CHUCVU'
ALTER TABLE [dbo].[CHITIET_CHUCVU]
ADD CONSTRAINT [PK_CHITIET_CHUCVU]
    PRIMARY KEY CLUSTERED ([CT_CV_ID] ASC);
GO

-- Creating primary key on [CTDG_MA] in table 'CHITIETDANHGIAs'
ALTER TABLE [dbo].[CHITIETDANHGIAs]
ADD CONSTRAINT [PK_CHITIETDANHGIAs]
    PRIMARY KEY CLUSTERED ([CTDG_MA] ASC);
GO

-- Creating primary key on [CV_MA] in table 'CHUCVUs'
ALTER TABLE [dbo].[CHUCVUs]
ADD CONSTRAINT [PK_CHUCVUs]
    PRIMARY KEY CLUSTERED ([CV_MA] ASC);
GO

-- Creating primary key on [CN_MA] in table 'CHUYENNGANHs'
ALTER TABLE [dbo].[CHUYENNGANHs]
ADD CONSTRAINT [PK_CHUYENNGANHs]
    PRIMARY KEY CLUSTERED ([CN_MA] ASC);
GO

-- Creating primary key on [CQ_MA] in table 'COQUANs'
ALTER TABLE [dbo].[COQUANs]
ADD CONSTRAINT [PK_COQUANs]
    PRIMARY KEY CLUSTERED ([CQ_MA] ASC);
GO

-- Creating primary key on [CSVC_MA] in table 'COSOVATCHATs'
ALTER TABLE [dbo].[COSOVATCHATs]
ADD CONSTRAINT [PK_COSOVATCHATs]
    PRIMARY KEY CLUSTERED ([CSVC_MA] ASC);
GO

-- Creating primary key on [DT_MA] in table 'DANTOCs'
ALTER TABLE [dbo].[DANTOCs]
ADD CONSTRAINT [PK_DANTOCs]
    PRIMARY KEY CLUSTERED ([DT_MA] ASC);
GO

-- Creating primary key on [HT_MA] in table 'HINHTHUCs'
ALTER TABLE [dbo].[HINHTHUCs]
ADD CONSTRAINT [PK_HINHTHUCs]
    PRIMARY KEY CLUSTERED ([HT_MA] ASC);
GO

-- Creating primary key on [HK_MA] in table 'HOCKies'
ALTER TABLE [dbo].[HOCKies]
ADD CONSTRAINT [PK_HOCKies]
    PRIMARY KEY CLUSTERED ([HK_MA] ASC);
GO

-- Creating primary key on [HS_MA] in table 'HOCSINHs'
ALTER TABLE [dbo].[HOCSINHs]
ADD CONSTRAINT [PK_HOCSINHs]
    PRIMARY KEY CLUSTERED ([HS_MA] ASC);
GO

-- Creating primary key on [KT_MA] in table 'KHENTHUONGs'
ALTER TABLE [dbo].[KHENTHUONGs]
ADD CONSTRAINT [PK_KHENTHUONGs]
    PRIMARY KEY CLUSTERED ([KT_MA] ASC);
GO

-- Creating primary key on [KHOI_MA] in table 'KHOIs'
ALTER TABLE [dbo].[KHOIs]
ADD CONSTRAINT [PK_KHOIs]
    PRIMARY KEY CLUSTERED ([KHOI_MA] ASC);
GO

-- Creating primary key on [KL_MA] in table 'KYLUATs'
ALTER TABLE [dbo].[KYLUATs]
ADD CONSTRAINT [PK_KYLUATs]
    PRIMARY KEY CLUSTERED ([KL_MA] ASC);
GO

-- Creating primary key on [LOP_MA] in table 'LOPs'
ALTER TABLE [dbo].[LOPs]
ADD CONSTRAINT [PK_LOPs]
    PRIMARY KEY CLUSTERED ([LOP_MA] ASC);
GO

-- Creating primary key on [MH_MA] in table 'MONHOCs'
ALTER TABLE [dbo].[MONHOCs]
ADD CONSTRAINT [PK_MONHOCs]
    PRIMARY KEY CLUSTERED ([MH_MA] ASC);
GO

-- Creating primary key on [NH_MA] in table 'NAMHOCs'
ALTER TABLE [dbo].[NAMHOCs]
ADD CONSTRAINT [PK_NAMHOCs]
    PRIMARY KEY CLUSTERED ([NH_MA] ASC);
GO

-- Creating primary key on [NL_MA] in table 'NGACHLUONGs'
ALTER TABLE [dbo].[NGACHLUONGs]
ADD CONSTRAINT [PK_NGACHLUONGs]
    PRIMARY KEY CLUSTERED ([NL_MA] ASC);
GO

-- Creating primary key on [PH_MA] in table 'PHONGHOCs'
ALTER TABLE [dbo].[PHONGHOCs]
ADD CONSTRAINT [PK_PHONGHOCs]
    PRIMARY KEY CLUSTERED ([PH_MA] ASC);
GO

-- Creating primary key on [QH_MA] in table 'QUANHUYENs'
ALTER TABLE [dbo].[QUANHUYENs]
ADD CONSTRAINT [PK_QUANHUYENs]
    PRIMARY KEY CLUSTERED ([QH_MA] ASC);
GO

-- Creating primary key on [SDG_MA] in table 'SODANHGIAs'
ALTER TABLE [dbo].[SODANHGIAs]
ADD CONSTRAINT [PK_SODANHGIAs]
    PRIMARY KEY CLUSTERED ([SDG_MA] ASC);
GO

-- Creating primary key on [TBDH_MA] in table 'THIETBIDAYHOCs'
ALTER TABLE [dbo].[THIETBIDAYHOCs]
ADD CONSTRAINT [PK_THIETBIDAYHOCs]
    PRIMARY KEY CLUSTERED ([TBDH_MA] ASC);
GO

-- Creating primary key on [TBGD_MA] in table 'THIETBIGIANGDAYs'
ALTER TABLE [dbo].[THIETBIGIANGDAYs]
ADD CONSTRAINT [PK_THIETBIGIANGDAYs]
    PRIMARY KEY CLUSTERED ([TBGD_MA] ASC);
GO

-- Creating primary key on [TKB_MA] in table 'THOIKHOABIEUs'
ALTER TABLE [dbo].[THOIKHOABIEUs]
ADD CONSTRAINT [PK_THOIKHOABIEUs]
    PRIMARY KEY CLUSTERED ([TKB_MA] ASC);
GO

-- Creating primary key on [TTDT_MA] in table 'THONGTINDAOTAOs'
ALTER TABLE [dbo].[THONGTINDAOTAOs]
ADD CONSTRAINT [PK_THONGTINDAOTAOs]
    PRIMARY KEY CLUSTERED ([TTDT_MA] ASC);
GO

-- Creating primary key on [TTL_MA] in table 'THONGTINLUONGs'
ALTER TABLE [dbo].[THONGTINLUONGs]
ADD CONSTRAINT [PK_THONGTINLUONGs]
    PRIMARY KEY CLUSTERED ([TTL_MA] ASC);
GO

-- Creating primary key on [THU_MA] in table 'THUs'
ALTER TABLE [dbo].[THUs]
ADD CONSTRAINT [PK_THUs]
    PRIMARY KEY CLUSTERED ([THU_MA] ASC);
GO

-- Creating primary key on [TH_MA] in table 'TIETHOCs'
ALTER TABLE [dbo].[TIETHOCs]
ADD CONSTRAINT [PK_TIETHOCs]
    PRIMARY KEY CLUSTERED ([TH_MA] ASC);
GO

-- Creating primary key on [TT_MA] in table 'TINHTHANHs'
ALTER TABLE [dbo].[TINHTHANHs]
ADD CONSTRAINT [PK_TINHTHANHs]
    PRIMARY KEY CLUSTERED ([TT_MA] ASC);
GO

-- Creating primary key on [TT_MA] in table 'TINHTRANGs'
ALTER TABLE [dbo].[TINHTRANGs]
ADD CONSTRAINT [PK_TINHTRANGs]
    PRIMARY KEY CLUSTERED ([TT_MA] ASC);
GO

-- Creating primary key on [Id] in table 'UpdateImages'
ALTER TABLE [dbo].[UpdateImages]
ADD CONSTRAINT [PK_UpdateImages]
    PRIMARY KEY CLUSTERED ([Id] ASC);
GO

-- Creating primary key on [VB_MA] in table 'VANBANGs'
ALTER TABLE [dbo].[VANBANGs]
ADD CONSTRAINT [PK_VANBANGs]
    PRIMARY KEY CLUSTERED ([VB_MA] ASC);
GO

-- Creating primary key on [XP_MA] in table 'XAPHUONGs'
ALTER TABLE [dbo].[XAPHUONGs]
ADD CONSTRAINT [PK_XAPHUONGs]
    PRIMARY KEY CLUSTERED ([XP_MA] ASC);
GO

-- Creating primary key on [KTCB_MA] in table 'KHENTHUONGCBs'
ALTER TABLE [dbo].[KHENTHUONGCBs]
ADD CONSTRAINT [PK_KHENTHUONGCBs]
    PRIMARY KEY CLUSTERED ([KTCB_MA] ASC);
GO

-- Creating primary key on [KLCB_MA] in table 'KYLUATCBs'
ALTER TABLE [dbo].[KYLUATCBs]
ADD CONSTRAINT [PK_KYLUATCBs]
    PRIMARY KEY CLUSTERED ([KLCB_MA] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [BACLUONG_BL_MA] in table 'THONGTINLUONGs'
ALTER TABLE [dbo].[THONGTINLUONGs]
ADD CONSTRAINT [FK_BACLUONGTHONGTINLUONG]
    FOREIGN KEY ([BACLUONG_BL_MA])
    REFERENCES [dbo].[BACLUONGs]
        ([BL_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BACLUONGTHONGTINLUONG'
CREATE INDEX [IX_FK_BACLUONGTHONGTINLUONG]
ON [dbo].[THONGTINLUONGs]
    ([BACLUONG_BL_MA]);
GO

-- Creating foreign key on [CANBO_CB_MA] in table 'CHITIET_CHUCVU'
ALTER TABLE [dbo].[CHITIET_CHUCVU]
ADD CONSTRAINT [FK_CANBOCHITIET_CHUCVU]
    FOREIGN KEY ([CANBO_CB_MA])
    REFERENCES [dbo].[CANBOes]
        ([CB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CANBOCHITIET_CHUCVU'
CREATE INDEX [IX_FK_CANBOCHITIET_CHUCVU]
ON [dbo].[CHITIET_CHUCVU]
    ([CANBO_CB_MA]);
GO

-- Creating foreign key on [CANBO_CB_MA] in table 'THONGTINDAOTAOs'
ALTER TABLE [dbo].[THONGTINDAOTAOs]
ADD CONSTRAINT [FK_CANBOTHONGTINDAOTAO]
    FOREIGN KEY ([CANBO_CB_MA])
    REFERENCES [dbo].[CANBOes]
        ([CB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CANBOTHONGTINDAOTAO'
CREATE INDEX [IX_FK_CANBOTHONGTINDAOTAO]
ON [dbo].[THONGTINDAOTAOs]
    ([CANBO_CB_MA]);
GO

-- Creating foreign key on [THONGTINLUONGs_TTL_MA] in table 'CANBOes'
ALTER TABLE [dbo].[CANBOes]
ADD CONSTRAINT [FK_CANBOTHONGTINLUONG]
    FOREIGN KEY ([THONGTINLUONGs_TTL_MA])
    REFERENCES [dbo].[THONGTINLUONGs]
        ([TTL_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CANBOTHONGTINLUONG'
CREATE INDEX [IX_FK_CANBOTHONGTINLUONG]
ON [dbo].[CANBOes]
    ([THONGTINLUONGs_TTL_MA]);
GO

-- Creating foreign key on [COQUAN_CQ_MA] in table 'CANBOes'
ALTER TABLE [dbo].[CANBOes]
ADD CONSTRAINT [FK_COQUANCANBO]
    FOREIGN KEY ([COQUAN_CQ_MA])
    REFERENCES [dbo].[COQUANs]
        ([CQ_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COQUANCANBO'
CREATE INDEX [IX_FK_COQUANCANBO]
ON [dbo].[CANBOes]
    ([COQUAN_CQ_MA]);
GO

-- Creating foreign key on [CHUCVU_CV_MA] in table 'CHITIET_CHUCVU'
ALTER TABLE [dbo].[CHITIET_CHUCVU]
ADD CONSTRAINT [FK_CHUCVUCHITIET_CHUCVU]
    FOREIGN KEY ([CHUCVU_CV_MA])
    REFERENCES [dbo].[CHUCVUs]
        ([CV_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CHUCVUCHITIET_CHUCVU'
CREATE INDEX [IX_FK_CHUCVUCHITIET_CHUCVU]
ON [dbo].[CHITIET_CHUCVU]
    ([CHUCVU_CV_MA]);
GO

-- Creating foreign key on [HOCSINH_HS_MA] in table 'CHITIETDANHGIAs'
ALTER TABLE [dbo].[CHITIETDANHGIAs]
ADD CONSTRAINT [FK_HOCSINHCHITIETDANHGIA]
    FOREIGN KEY ([HOCSINH_HS_MA])
    REFERENCES [dbo].[HOCSINHs]
        ([HS_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_HOCSINHCHITIETDANHGIA'
CREATE INDEX [IX_FK_HOCSINHCHITIETDANHGIA]
ON [dbo].[CHITIETDANHGIAs]
    ([HOCSINH_HS_MA]);
GO

-- Creating foreign key on [SODANHGIA_SDG_MA] in table 'CHITIETDANHGIAs'
ALTER TABLE [dbo].[CHITIETDANHGIAs]
ADD CONSTRAINT [FK_SODANHGIACHITIETDANHGIA]
    FOREIGN KEY ([SODANHGIA_SDG_MA])
    REFERENCES [dbo].[SODANHGIAs]
        ([SDG_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SODANHGIACHITIETDANHGIA'
CREATE INDEX [IX_FK_SODANHGIACHITIETDANHGIA]
ON [dbo].[CHITIETDANHGIAs]
    ([SODANHGIA_SDG_MA]);
GO

-- Creating foreign key on [THONGTINDAOTAO_TTDT_MA] in table 'CHUYENNGANHs'
ALTER TABLE [dbo].[CHUYENNGANHs]
ADD CONSTRAINT [FK_THONGTINDAOTAOCHUYENNGANH]
    FOREIGN KEY ([THONGTINDAOTAO_TTDT_MA])
    REFERENCES [dbo].[THONGTINDAOTAOs]
        ([TTDT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THONGTINDAOTAOCHUYENNGANH'
CREATE INDEX [IX_FK_THONGTINDAOTAOCHUYENNGANH]
ON [dbo].[CHUYENNGANHs]
    ([THONGTINDAOTAO_TTDT_MA]);
GO

-- Creating foreign key on [COSOVATCHAT_CSVC_MA] in table 'THIETBIDAYHOCs'
ALTER TABLE [dbo].[THIETBIDAYHOCs]
ADD CONSTRAINT [FK_COSOVATCHATTHIETBIDAYHOC]
    FOREIGN KEY ([COSOVATCHAT_CSVC_MA])
    REFERENCES [dbo].[COSOVATCHATs]
        ([CSVC_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COSOVATCHATTHIETBIDAYHOC'
CREATE INDEX [IX_FK_COSOVATCHATTHIETBIDAYHOC]
ON [dbo].[THIETBIDAYHOCs]
    ([COSOVATCHAT_CSVC_MA]);
GO

-- Creating foreign key on [COSOVATCHAT_CSVC_MA] in table 'THIETBIGIANGDAYs'
ALTER TABLE [dbo].[THIETBIGIANGDAYs]
ADD CONSTRAINT [FK_COSOVATCHATTHIETBIGIANGDAY]
    FOREIGN KEY ([COSOVATCHAT_CSVC_MA])
    REFERENCES [dbo].[COSOVATCHATs]
        ([CSVC_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COSOVATCHATTHIETBIGIANGDAY'
CREATE INDEX [IX_FK_COSOVATCHATTHIETBIGIANGDAY]
ON [dbo].[THIETBIGIANGDAYs]
    ([COSOVATCHAT_CSVC_MA]);
GO

-- Creating foreign key on [COSOVATCHAT_CSVC_MA] in table 'TINHTRANGs'
ALTER TABLE [dbo].[TINHTRANGs]
ADD CONSTRAINT [FK_COSOVATCHATTINHTRANG]
    FOREIGN KEY ([COSOVATCHAT_CSVC_MA])
    REFERENCES [dbo].[COSOVATCHATs]
        ([CSVC_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COSOVATCHATTINHTRANG'
CREATE INDEX [IX_FK_COSOVATCHATTINHTRANG]
ON [dbo].[TINHTRANGs]
    ([COSOVATCHAT_CSVC_MA]);
GO

-- Creating foreign key on [PHONGHOC_PH_MA] in table 'COSOVATCHATs'
ALTER TABLE [dbo].[COSOVATCHATs]
ADD CONSTRAINT [FK_PHONGHOCCOSOVATCHAT]
    FOREIGN KEY ([PHONGHOC_PH_MA])
    REFERENCES [dbo].[PHONGHOCs]
        ([PH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PHONGHOCCOSOVATCHAT'
CREATE INDEX [IX_FK_PHONGHOCCOSOVATCHAT]
ON [dbo].[COSOVATCHATs]
    ([PHONGHOC_PH_MA]);
GO

-- Creating foreign key on [DANTOC_DT_MA] in table 'HOCSINHs'
ALTER TABLE [dbo].[HOCSINHs]
ADD CONSTRAINT [FK_DANTOCHOCSINH]
    FOREIGN KEY ([DANTOC_DT_MA])
    REFERENCES [dbo].[DANTOCs]
        ([DT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DANTOCHOCSINH'
CREATE INDEX [IX_FK_DANTOCHOCSINH]
ON [dbo].[HOCSINHs]
    ([DANTOC_DT_MA]);
GO

-- Creating foreign key on [HINHTHUCs_HT_MA] in table 'THONGTINDAOTAOs'
ALTER TABLE [dbo].[THONGTINDAOTAOs]
ADD CONSTRAINT [FK_THONGTINDAOTAOHINHTHUC]
    FOREIGN KEY ([HINHTHUCs_HT_MA])
    REFERENCES [dbo].[HINHTHUCs]
        ([HT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THONGTINDAOTAOHINHTHUC'
CREATE INDEX [IX_FK_THONGTINDAOTAOHINHTHUC]
ON [dbo].[THONGTINDAOTAOs]
    ([HINHTHUCs_HT_MA]);
GO

-- Creating foreign key on [HOCKy_HK_MA] in table 'SODANHGIAs'
ALTER TABLE [dbo].[SODANHGIAs]
ADD CONSTRAINT [FK_HOCKySODANHGIA]
    FOREIGN KEY ([HOCKy_HK_MA])
    REFERENCES [dbo].[HOCKies]
        ([HK_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_HOCKySODANHGIA'
CREATE INDEX [IX_FK_HOCKySODANHGIA]
ON [dbo].[SODANHGIAs]
    ([HOCKy_HK_MA]);
GO

-- Creating foreign key on [HOCSINH_HS_MA] in table 'KHENTHUONGs'
ALTER TABLE [dbo].[KHENTHUONGs]
ADD CONSTRAINT [FK_HOCSINHKHENTHUONG]
    FOREIGN KEY ([HOCSINH_HS_MA])
    REFERENCES [dbo].[HOCSINHs]
        ([HS_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_HOCSINHKHENTHUONG'
CREATE INDEX [IX_FK_HOCSINHKHENTHUONG]
ON [dbo].[KHENTHUONGs]
    ([HOCSINH_HS_MA]);
GO

-- Creating foreign key on [HOCSINH_HS_MA] in table 'KYLUATs'
ALTER TABLE [dbo].[KYLUATs]
ADD CONSTRAINT [FK_HOCSINHKYLUAT]
    FOREIGN KEY ([HOCSINH_HS_MA])
    REFERENCES [dbo].[HOCSINHs]
        ([HS_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_HOCSINHKYLUAT'
CREATE INDEX [IX_FK_HOCSINHKYLUAT]
ON [dbo].[KYLUATs]
    ([HOCSINH_HS_MA]);
GO

-- Creating foreign key on [LOP_LOP_MA] in table 'HOCSINHs'
ALTER TABLE [dbo].[HOCSINHs]
ADD CONSTRAINT [FK_LOPHOCSINH]
    FOREIGN KEY ([LOP_LOP_MA])
    REFERENCES [dbo].[LOPs]
        ([LOP_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LOPHOCSINH'
CREATE INDEX [IX_FK_LOPHOCSINH]
ON [dbo].[HOCSINHs]
    ([LOP_LOP_MA]);
GO

-- Creating foreign key on [QUANHUYEN_QH_MA] in table 'HOCSINHs'
ALTER TABLE [dbo].[HOCSINHs]
ADD CONSTRAINT [FK_QUANHUYENHOCSINH]
    FOREIGN KEY ([QUANHUYEN_QH_MA])
    REFERENCES [dbo].[QUANHUYENs]
        ([QH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_QUANHUYENHOCSINH'
CREATE INDEX [IX_FK_QUANHUYENHOCSINH]
ON [dbo].[HOCSINHs]
    ([QUANHUYEN_QH_MA]);
GO

-- Creating foreign key on [TINHTHANH_TT_MA] in table 'HOCSINHs'
ALTER TABLE [dbo].[HOCSINHs]
ADD CONSTRAINT [FK_TINHTHANHHOCSINH]
    FOREIGN KEY ([TINHTHANH_TT_MA])
    REFERENCES [dbo].[TINHTHANHs]
        ([TT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TINHTHANHHOCSINH'
CREATE INDEX [IX_FK_TINHTHANHHOCSINH]
ON [dbo].[HOCSINHs]
    ([TINHTHANH_TT_MA]);
GO

-- Creating foreign key on [XAPHUONG_XP_MA] in table 'HOCSINHs'
ALTER TABLE [dbo].[HOCSINHs]
ADD CONSTRAINT [FK_XAPHUONGHOCSINH]
    FOREIGN KEY ([XAPHUONG_XP_MA])
    REFERENCES [dbo].[XAPHUONGs]
        ([XP_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_XAPHUONGHOCSINH'
CREATE INDEX [IX_FK_XAPHUONGHOCSINH]
ON [dbo].[HOCSINHs]
    ([XAPHUONG_XP_MA]);
GO

-- Creating foreign key on [KHOIs_KHOI_MA] in table 'LOPs'
ALTER TABLE [dbo].[LOPs]
ADD CONSTRAINT [FK_KHOIsLOP]
    FOREIGN KEY ([KHOIs_KHOI_MA])
    REFERENCES [dbo].[KHOIs]
        ([KHOI_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KHOIsLOP'
CREATE INDEX [IX_FK_KHOIsLOP]
ON [dbo].[LOPs]
    ([KHOIs_KHOI_MA]);
GO

-- Creating foreign key on [LOP_LOP_MA] in table 'THOIKHOABIEUs'
ALTER TABLE [dbo].[THOIKHOABIEUs]
ADD CONSTRAINT [FK_LOPTHOIKHOABIEU]
    FOREIGN KEY ([LOP_LOP_MA])
    REFERENCES [dbo].[LOPs]
        ([LOP_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LOPTHOIKHOABIEU'
CREATE INDEX [IX_FK_LOPTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEUs]
    ([LOP_LOP_MA]);
GO

-- Creating foreign key on [NAMHOC_NH_MA] in table 'LOPs'
ALTER TABLE [dbo].[LOPs]
ADD CONSTRAINT [FK_NAMHOCLOP]
    FOREIGN KEY ([NAMHOC_NH_MA])
    REFERENCES [dbo].[NAMHOCs]
        ([NH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_NAMHOCLOP'
CREATE INDEX [IX_FK_NAMHOCLOP]
ON [dbo].[LOPs]
    ([NAMHOC_NH_MA]);
GO

-- Creating foreign key on [THOIKHOABIEU_TKB_MA] in table 'MONHOCs'
ALTER TABLE [dbo].[MONHOCs]
ADD CONSTRAINT [FK_THOIKHOABIEUMONHOC]
    FOREIGN KEY ([THOIKHOABIEU_TKB_MA])
    REFERENCES [dbo].[THOIKHOABIEUs]
        ([TKB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THOIKHOABIEUMONHOC'
CREATE INDEX [IX_FK_THOIKHOABIEUMONHOC]
ON [dbo].[MONHOCs]
    ([THOIKHOABIEU_TKB_MA]);
GO

-- Creating foreign key on [NGACHLUONG_NL_MA] in table 'THONGTINLUONGs'
ALTER TABLE [dbo].[THONGTINLUONGs]
ADD CONSTRAINT [FK_NGACHLUONGTHONGTINLUONG]
    FOREIGN KEY ([NGACHLUONG_NL_MA])
    REFERENCES [dbo].[NGACHLUONGs]
        ([NL_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_NGACHLUONGTHONGTINLUONG'
CREATE INDEX [IX_FK_NGACHLUONGTHONGTINLUONG]
ON [dbo].[THONGTINLUONGs]
    ([NGACHLUONG_NL_MA]);
GO

-- Creating foreign key on [THOIKHOABIEU_TKB_MA] in table 'THUs'
ALTER TABLE [dbo].[THUs]
ADD CONSTRAINT [FK_THOIKHOABIEUTHU]
    FOREIGN KEY ([THOIKHOABIEU_TKB_MA])
    REFERENCES [dbo].[THOIKHOABIEUs]
        ([TKB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THOIKHOABIEUTHU'
CREATE INDEX [IX_FK_THOIKHOABIEUTHU]
ON [dbo].[THUs]
    ([THOIKHOABIEU_TKB_MA]);
GO

-- Creating foreign key on [THOIKHOABIEU_TKB_MA] in table 'TIETHOCs'
ALTER TABLE [dbo].[TIETHOCs]
ADD CONSTRAINT [FK_THOIKHOABIEUTIETHOC]
    FOREIGN KEY ([THOIKHOABIEU_TKB_MA])
    REFERENCES [dbo].[THOIKHOABIEUs]
        ([TKB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THOIKHOABIEUTIETHOC'
CREATE INDEX [IX_FK_THOIKHOABIEUTIETHOC]
ON [dbo].[TIETHOCs]
    ([THOIKHOABIEU_TKB_MA]);
GO

-- Creating foreign key on [THONGTINDAOTAO_TTDT_MA] in table 'VANBANGs'
ALTER TABLE [dbo].[VANBANGs]
ADD CONSTRAINT [FK_THONGTINDAOTAOVANBANG]
    FOREIGN KEY ([THONGTINDAOTAO_TTDT_MA])
    REFERENCES [dbo].[THONGTINDAOTAOs]
        ([TTDT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THONGTINDAOTAOVANBANG'
CREATE INDEX [IX_FK_THONGTINDAOTAOVANBANG]
ON [dbo].[VANBANGs]
    ([THONGTINDAOTAO_TTDT_MA]);
GO

-- Creating foreign key on [CANBOes_CB_MA] in table 'KHENTHUONGCBs'
ALTER TABLE [dbo].[KHENTHUONGCBs]
ADD CONSTRAINT [FK_CANBOKHENTHUONGCB]
    FOREIGN KEY ([CANBOes_CB_MA])
    REFERENCES [dbo].[CANBOes]
        ([CB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CANBOKHENTHUONGCB'
CREATE INDEX [IX_FK_CANBOKHENTHUONGCB]
ON [dbo].[KHENTHUONGCBs]
    ([CANBOes_CB_MA]);
GO

-- Creating foreign key on [CANBOes_CB_MA] in table 'KYLUATCBs'
ALTER TABLE [dbo].[KYLUATCBs]
ADD CONSTRAINT [FK_CANBOKYLUATCB]
    FOREIGN KEY ([CANBOes_CB_MA])
    REFERENCES [dbo].[CANBOes]
        ([CB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CANBOKYLUATCB'
CREATE INDEX [IX_FK_CANBOKYLUATCB]
ON [dbo].[KYLUATCBs]
    ([CANBOes_CB_MA]);
GO

-- Creating foreign key on [CANBO_CB_MA] in table 'THOIKHOABIEUs'
ALTER TABLE [dbo].[THOIKHOABIEUs]
ADD CONSTRAINT [FK_CANBOTHOIKHOABIEU]
    FOREIGN KEY ([CANBO_CB_MA])
    REFERENCES [dbo].[CANBOes]
        ([CB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CANBOTHOIKHOABIEU'
CREATE INDEX [IX_FK_CANBOTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEUs]
    ([CANBO_CB_MA]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------