

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLTHPT.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class acomptec_qlthptEntities3 : DbContext
{
    public acomptec_qlthptEntities3()
        : base("name=acomptec_qlthptEntities3")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CHITIETDANHGIA> CHITIETDANHGIA { get; set; }

    public virtual DbSet<KHENTHUONG> KHENTHUONG { get; set; }

    public virtual DbSet<KHOI> KHOI { get; set; }

    public virtual DbSet<KYLUAT> KYLUAT { get; set; }

    public virtual DbSet<LOP> LOP { get; set; }

    public virtual DbSet<NAMHOC> NAMHOC { get; set; }

    public virtual DbSet<THOIKHOABIEU> THOIKHOABIEU { get; set; }

    public virtual DbSet<UpdateImage> UpdateImages { get; set; }

    public virtual DbSet<BACLUONG> BACLUONG { get; set; }

    public virtual DbSet<CANBO> CANBO { get; set; }

    public virtual DbSet<CHUCVU> CHUCVU { get; set; }

    public virtual DbSet<CHUYENNGANH> CHUYENNGANH { get; set; }

    public virtual DbSet<COQUAN> COQUAN { get; set; }

    public virtual DbSet<COSOVATCHAT> COSOVATCHAT { get; set; }

    public virtual DbSet<DANTOC> DANTOC { get; set; }

    public virtual DbSet<HINHTHUC> HINHTHUC { get; set; }

    public virtual DbSet<HOCSINH> HOCSINH { get; set; }

    public virtual DbSet<MONHOC> MONHOC { get; set; }

    public virtual DbSet<NGACHLUONG> NGACHLUONG { get; set; }

    public virtual DbSet<PHONGHOC> PHONGHOC { get; set; }

    public virtual DbSet<QUANHUYEN> QUANHUYEN { get; set; }

    public virtual DbSet<SODANHGIA> SODANHGIA { get; set; }

    public virtual DbSet<THIETBIDAYHOC> THIETBIDAYHOC { get; set; }

    public virtual DbSet<THIETBIGIANGDAY> THIETBIGIANGDAY { get; set; }

    public virtual DbSet<THONGTINDAOTAO> THONGTINDAOTAO { get; set; }

    public virtual DbSet<THONGTINLUONG> THONGTINLUONG { get; set; }

    public virtual DbSet<THU> THU { get; set; }

    public virtual DbSet<TIETHOC> TIETHOC { get; set; }

    public virtual DbSet<TINHTHANH> TINHTHANH { get; set; }

    public virtual DbSet<TINHTRANG> TINHTRANG { get; set; }

    public virtual DbSet<VANBANG> VANBANG { get; set; }

    public virtual DbSet<XAPHUONG> XAPHUONG { get; set; }

    public virtual DbSet<CHITIET_CHUCVU> CHITIET_CHUCVU { get; set; }

    public virtual DbSet<HOCKY> HOCKY { get; set; }

    public virtual DbSet<KHENTHUONGCB> KHENTHUONGCB { get; set; }

    public virtual DbSet<KYLUATCB> KYLUATCB { get; set; }

}

}

