
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 04/08/2020 00:11:33
-- Generated from EDMX file: C:\Users\OS\Documents\QLTHPT\QLTHPT\Models\ModelDB.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [acomptec_qlthpt];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_SODANHGIACHITIETDANHGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHITIETDANHGIA] DROP CONSTRAINT [FK_SODANHGIACHITIETDANHGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_PHONGHOCCOSOVATCHAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COSOVATCHAT] DROP CONSTRAINT [FK_PHONGHOCCOSOVATCHAT];
GO
IF OBJECT_ID(N'[dbo].[FK_BACLUONGTHONGTINLUONG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINLUONG] DROP CONSTRAINT [FK_BACLUONGTHONGTINLUONG];
GO
IF OBJECT_ID(N'[dbo].[FK_NGACHLUONGTHONGTINLUONG]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINLUONG] DROP CONSTRAINT [FK_NGACHLUONGTHONGTINLUONG];
GO
IF OBJECT_ID(N'[dbo].[FK_LOPTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEU] DROP CONSTRAINT [FK_LOPTHOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[FK_THONGTINDAOTAOHINHTHUC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINDAOTAO] DROP CONSTRAINT [FK_THONGTINDAOTAOHINHTHUC];
GO
IF OBJECT_ID(N'[dbo].[FK_CHUCVUCHITIET_CHUCVU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHITIET_CHUCVU] DROP CONSTRAINT [FK_CHUCVUCHITIET_CHUCVU];
GO
IF OBJECT_ID(N'[dbo].[FK_MONHOCTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEU] DROP CONSTRAINT [FK_MONHOCTHOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[FK_CHUYENNGANHTHONGTINDAOTAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINDAOTAO] DROP CONSTRAINT [FK_CHUYENNGANHTHONGTINDAOTAO];
GO
IF OBJECT_ID(N'[dbo].[FK_THUTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEU] DROP CONSTRAINT [FK_THUTHOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[FK_TIETHOCTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEU] DROP CONSTRAINT [FK_TIETHOCTHOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[FK_VANBANGTHONGTINDAOTAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THONGTINDAOTAO] DROP CONSTRAINT [FK_VANBANGTHONGTINDAOTAO];
GO
IF OBJECT_ID(N'[dbo].[FK_THIETBIGIANGDAYCOSOVATCHAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COSOVATCHAT] DROP CONSTRAINT [FK_THIETBIGIANGDAYCOSOVATCHAT];
GO
IF OBJECT_ID(N'[dbo].[FK_THIETBIDAYHOCCOSOVATCHAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COSOVATCHAT] DROP CONSTRAINT [FK_THIETBIDAYHOCCOSOVATCHAT];
GO
IF OBJECT_ID(N'[dbo].[FK_TINHTRANGCOSOVATCHAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COSOVATCHAT] DROP CONSTRAINT [FK_TINHTRANGCOSOVATCHAT];
GO
IF OBJECT_ID(N'[dbo].[FK_TINHTHANHHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_TINHTHANHHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_XAPHUONGHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_XAPHUONGHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_KYLUATHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_KYLUATHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_KHENTHUONGHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_KHENTHUONGHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_CHITIETDANHGIAHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_CHITIETDANHGIAHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_QUANHUYENHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_QUANHUYENHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_DANTOCHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_DANTOCHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_LOPHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_LOPHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_COQUANCANBO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBO] DROP CONSTRAINT [FK_COQUANCANBO];
GO
IF OBJECT_ID(N'[dbo].[FK_CHITIET_CHUCVUCANBO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBO] DROP CONSTRAINT [FK_CHITIET_CHUCVUCANBO];
GO
IF OBJECT_ID(N'[dbo].[FK_KYLUATCBCANBO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBO] DROP CONSTRAINT [FK_KYLUATCBCANBO];
GO
IF OBJECT_ID(N'[dbo].[FK_KHENTHUONGCBCANBO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBO] DROP CONSTRAINT [FK_KHENTHUONGCBCANBO];
GO
IF OBJECT_ID(N'[dbo].[FK_CANBOTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEU] DROP CONSTRAINT [FK_CANBOTHOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[FK_THONGTINDAOTAOCANBO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBO] DROP CONSTRAINT [FK_THONGTINDAOTAOCANBO];
GO
IF OBJECT_ID(N'[dbo].[FK_HOCKYTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEU] DROP CONSTRAINT [FK_HOCKYTHOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[FK_KHOIHOCSINH]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[HOCSINH] DROP CONSTRAINT [FK_KHOIHOCSINH];
GO
IF OBJECT_ID(N'[dbo].[FK_THONGTINLUONGCANBO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CANBO] DROP CONSTRAINT [FK_THONGTINLUONGCANBO];
GO
IF OBJECT_ID(N'[dbo].[FK_NAMHOCSODANHGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SODANHGIA] DROP CONSTRAINT [FK_NAMHOCSODANHGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_MONHOCCHITIETDANHGIA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CHITIETDANHGIA] DROP CONSTRAINT [FK_MONHOCCHITIETDANHGIA];
GO
IF OBJECT_ID(N'[dbo].[FK_NAMHOCTHOIKHOABIEU]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[THOIKHOABIEU] DROP CONSTRAINT [FK_NAMHOCTHOIKHOABIEU];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[CHITIETDANHGIA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHITIETDANHGIA];
GO
IF OBJECT_ID(N'[dbo].[KHENTHUONG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KHENTHUONG];
GO
IF OBJECT_ID(N'[dbo].[KHOI]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KHOI];
GO
IF OBJECT_ID(N'[dbo].[KYLUAT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KYLUAT];
GO
IF OBJECT_ID(N'[dbo].[LOP]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LOP];
GO
IF OBJECT_ID(N'[dbo].[NAMHOC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[NAMHOC];
GO
IF OBJECT_ID(N'[dbo].[THOIKHOABIEU]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THOIKHOABIEU];
GO
IF OBJECT_ID(N'[dbo].[UpdateImages]', 'U') IS NOT NULL
    DROP TABLE [dbo].[UpdateImages];
GO
IF OBJECT_ID(N'[dbo].[BACLUONG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BACLUONG];
GO
IF OBJECT_ID(N'[dbo].[CANBO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CANBO];
GO
IF OBJECT_ID(N'[dbo].[CHUCVU]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHUCVU];
GO
IF OBJECT_ID(N'[dbo].[CHUYENNGANH]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHUYENNGANH];
GO
IF OBJECT_ID(N'[dbo].[COQUAN]', 'U') IS NOT NULL
    DROP TABLE [dbo].[COQUAN];
GO
IF OBJECT_ID(N'[dbo].[COSOVATCHAT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[COSOVATCHAT];
GO
IF OBJECT_ID(N'[dbo].[DANTOC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DANTOC];
GO
IF OBJECT_ID(N'[dbo].[HINHTHUC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[HINHTHUC];
GO
IF OBJECT_ID(N'[dbo].[HOCSINH]', 'U') IS NOT NULL
    DROP TABLE [dbo].[HOCSINH];
GO
IF OBJECT_ID(N'[dbo].[MONHOC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MONHOC];
GO
IF OBJECT_ID(N'[dbo].[NGACHLUONG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[NGACHLUONG];
GO
IF OBJECT_ID(N'[dbo].[PHONGHOC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PHONGHOC];
GO
IF OBJECT_ID(N'[dbo].[QUANHUYEN]', 'U') IS NOT NULL
    DROP TABLE [dbo].[QUANHUYEN];
GO
IF OBJECT_ID(N'[dbo].[SODANHGIA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SODANHGIA];
GO
IF OBJECT_ID(N'[dbo].[THIETBIDAYHOC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THIETBIDAYHOC];
GO
IF OBJECT_ID(N'[dbo].[THIETBIGIANGDAY]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THIETBIGIANGDAY];
GO
IF OBJECT_ID(N'[dbo].[THONGTINDAOTAO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THONGTINDAOTAO];
GO
IF OBJECT_ID(N'[dbo].[THONGTINLUONG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THONGTINLUONG];
GO
IF OBJECT_ID(N'[dbo].[THU]', 'U') IS NOT NULL
    DROP TABLE [dbo].[THU];
GO
IF OBJECT_ID(N'[dbo].[TIETHOC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIETHOC];
GO
IF OBJECT_ID(N'[dbo].[TINHTHANH]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TINHTHANH];
GO
IF OBJECT_ID(N'[dbo].[TINHTRANG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TINHTRANG];
GO
IF OBJECT_ID(N'[dbo].[VANBANG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[VANBANG];
GO
IF OBJECT_ID(N'[dbo].[XAPHUONG]', 'U') IS NOT NULL
    DROP TABLE [dbo].[XAPHUONG];
GO
IF OBJECT_ID(N'[dbo].[CHITIET_CHUCVU]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CHITIET_CHUCVU];
GO
IF OBJECT_ID(N'[dbo].[HOCKY]', 'U') IS NOT NULL
    DROP TABLE [dbo].[HOCKY];
GO
IF OBJECT_ID(N'[dbo].[KHENTHUONGCB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KHENTHUONGCB];
GO
IF OBJECT_ID(N'[dbo].[KYLUATCB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[KYLUATCB];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'CHITIETDANHGIA'
CREATE TABLE [dbo].[CHITIETDANHGIA] (
    [CTDG_MA] varchar(10)  NOT NULL,
    [CTDG_NGAYDG] datetime  NULL,
    [SODANHGIA_SDG_MA] varchar(10)  NOT NULL,
    [MONHOC_MH_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'KHENTHUONG'
CREATE TABLE [dbo].[KHENTHUONG] (
    [KT_MA] varchar(10)  NOT NULL,
    [KT_THANHTICH] nvarchar(50)  NULL,
    [KT_NGAYKHENTHUONG] datetime  NULL,
    [KT_GHICHU] nvarchar(100)  NULL
);
GO

-- Creating table 'KHOI'
CREATE TABLE [dbo].[KHOI] (
    [KHOI_MA] varchar(10)  NOT NULL,
    [KHOI_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'KYLUAT'
CREATE TABLE [dbo].[KYLUAT] (
    [KL_MA] varchar(10)  NOT NULL,
    [KL_HINHTHUC] nvarchar(50)  NULL,
    [KL_NGAYKYLUAT] datetime  NULL
);
GO

-- Creating table 'LOP'
CREATE TABLE [dbo].[LOP] (
    [LOP_MA] varchar(10)  NOT NULL,
    [LOP_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'NAMHOC'
CREATE TABLE [dbo].[NAMHOC] (
    [NH_MA] varchar(10)  NOT NULL,
    [NH_NAMHOC] nvarchar(50)  NULL
);
GO

-- Creating table 'THOIKHOABIEU'
CREATE TABLE [dbo].[THOIKHOABIEU] (
    [TKB_MA] varchar(10)  NOT NULL,
    [LOP_LOP_MA] varchar(10)  NOT NULL,
    [MONHOC_MH_MA] varchar(10)  NOT NULL,
    [THU_THU_MA] varchar(10)  NOT NULL,
    [TIETHOC_TH_MA] varchar(10)  NOT NULL,
    [CANBO_CB_MA] varchar(10)  NOT NULL,
    [HOCKY_HK_MA] varchar(200)  NOT NULL
);
GO

-- Creating table 'UpdateImages'
CREATE TABLE [dbo].[UpdateImages] (
    [Id] varchar(50)  NOT NULL,
    [Image_url] nvarchar(100)  NULL,
    [Name_im] nvarchar(100)  NULL
);
GO

-- Creating table 'BACLUONG'
CREATE TABLE [dbo].[BACLUONG] (
    [BL_MA] varchar(10)  NOT NULL,
    [BL_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'CANBO'
CREATE TABLE [dbo].[CANBO] (
    [CB_MA] varchar(10)  NOT NULL,
    [CB_HOTEN] nvarchar(50)  NOT NULL,
    [CB_GIOITINH] varchar(10)  NULL,
    [CB_DIACHI] nvarchar(200)  NULL,
    [CB_NGAYSINH] datetime  NULL,
    [CB_CMND] varchar(20)  NOT NULL,
    [COQUAN_CQ_MA] varchar(10)  NOT NULL,
    [CHITIET_CHUCVU_CT_CV_ID] time  NOT NULL,
    [KYLUATCB_KLCB_MA] varchar(200)  NOT NULL,
    [KHENTHUONGCB_KTCB_MA] varchar(200)  NOT NULL,
    [THONGTINDAOTAO_TTDT_MA] varchar(10)  NOT NULL,
    [THONGTINLUONG_TTL_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'CHUCVU'
CREATE TABLE [dbo].[CHUCVU] (
    [CV_MA] varchar(10)  NOT NULL,
    [CV_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'CHUYENNGANH'
CREATE TABLE [dbo].[CHUYENNGANH] (
    [CN_MA] varchar(10)  NOT NULL,
    [CN_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'COQUAN'
CREATE TABLE [dbo].[COQUAN] (
    [CQ_MA] varchar(10)  NOT NULL,
    [CQ_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'COSOVATCHAT'
CREATE TABLE [dbo].[COSOVATCHAT] (
    [CSVC_MA] varchar(10)  NOT NULL,
    [CSVC_SOLUONG] int  NOT NULL,
    [PHONGHOC_PH_MA] varchar(10)  NOT NULL,
    [THIETBIGIANGDAY_TBGD_MA] varchar(10)  NOT NULL,
    [THIETBIDAYHOC_TBDH_MA] varchar(10)  NOT NULL,
    [TINHTRANG_TT_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'DANTOC'
CREATE TABLE [dbo].[DANTOC] (
    [DT_MA] varchar(10)  NOT NULL,
    [DT_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'HINHTHUC'
CREATE TABLE [dbo].[HINHTHUC] (
    [HT_MA] varchar(10)  NOT NULL,
    [HT_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'HOCSINH'
CREATE TABLE [dbo].[HOCSINH] (
    [HS_MA] varchar(10)  NOT NULL,
    [HS_HOTEN] nvarchar(50)  NOT NULL,
    [HS_GIOITINH] varchar(10)  NULL,
    [HS_NGAYSINH] datetime  NOT NULL,
    [HS_TONGIAO] nvarchar(20)  NULL,
    [TINHTHANH_TT_MA] varchar(10)  NOT NULL,
    [XAPHUONG_XP_MA] varchar(10)  NOT NULL,
    [KYLUAT_KL_MA] varchar(10)  NOT NULL,
    [KHENTHUONG_KT_MA] varchar(10)  NOT NULL,
    [CHITIETDANHGIA_CTDG_MA] varchar(10)  NOT NULL,
    [QUANHUYEN_QH_MA] varchar(10)  NOT NULL,
    [DANTOC_DT_MA] varchar(10)  NOT NULL,
    [LOP_LOP_MA] varchar(10)  NOT NULL,
    [KHOI_KHOI_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'MONHOC'
CREATE TABLE [dbo].[MONHOC] (
    [MH_MA] varchar(10)  NOT NULL,
    [MH_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'NGACHLUONG'
CREATE TABLE [dbo].[NGACHLUONG] (
    [NL_MA] varchar(10)  NOT NULL,
    [NL_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'PHONGHOC'
CREATE TABLE [dbo].[PHONGHOC] (
    [PH_MA] varchar(10)  NOT NULL,
    [PH_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'QUANHUYEN'
CREATE TABLE [dbo].[QUANHUYEN] (
    [QH_MA] varchar(10)  NOT NULL,
    [QH_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'SODANHGIA'
CREATE TABLE [dbo].[SODANHGIA] (
    [SDG_MA] varchar(10)  NOT NULL,
    [SDG_DIEM] varchar(10)  NULL,
    [SDG_GHICHU] nvarchar(50)  NULL,
    [NAMHOC_NH_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THIETBIDAYHOC'
CREATE TABLE [dbo].[THIETBIDAYHOC] (
    [TBDH_MA] varchar(10)  NOT NULL,
    [TBDH_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'THIETBIGIANGDAY'
CREATE TABLE [dbo].[THIETBIGIANGDAY] (
    [TBGD_MA] varchar(10)  NOT NULL,
    [TBGD_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'THONGTINDAOTAO'
CREATE TABLE [dbo].[THONGTINDAOTAO] (
    [TTDT_MA] varchar(10)  NOT NULL,
    [HINHTHUCs_HT_MA] varchar(10)  NOT NULL,
    [CHUYENNGANH_CN_MA] varchar(10)  NOT NULL,
    [VANBANG_VB_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THONGTINLUONG'
CREATE TABLE [dbo].[THONGTINLUONG] (
    [TTL_MA] varchar(10)  NOT NULL,
    [TTL_NGAYNHANLUONG] nvarchar(50)  NULL,
    [TTL_HESOLUONG] varchar(10)  NULL,
    [BACLUONG_BL_MA] varchar(10)  NOT NULL,
    [NGACHLUONG_NL_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'THU'
CREATE TABLE [dbo].[THU] (
    [THU_MA] varchar(10)  NOT NULL,
    [THU_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'TIETHOC'
CREATE TABLE [dbo].[TIETHOC] (
    [TH_MA] varchar(10)  NOT NULL,
    [TH_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'TINHTHANH'
CREATE TABLE [dbo].[TINHTHANH] (
    [TT_MA] varchar(10)  NOT NULL,
    [TT_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'TINHTRANG'
CREATE TABLE [dbo].[TINHTRANG] (
    [TT_MA] varchar(10)  NOT NULL,
    [TT_MOTA] nvarchar(200)  NULL
);
GO

-- Creating table 'VANBANG'
CREATE TABLE [dbo].[VANBANG] (
    [VB_MA] varchar(10)  NOT NULL,
    [VB_TEN] nvarchar(50)  NULL
);
GO

-- Creating table 'XAPHUONG'
CREATE TABLE [dbo].[XAPHUONG] (
    [XP_MA] varchar(10)  NOT NULL,
    [XP_TEN] nvarchar(50)  NOT NULL
);
GO

-- Creating table 'CHITIET_CHUCVU'
CREATE TABLE [dbo].[CHITIET_CHUCVU] (
    [CT_CV_ID] time  NOT NULL,
    [CT_CV_TEN] nvarchar(max)  NOT NULL,
    [CHUCVU_CV_MA] varchar(10)  NOT NULL
);
GO

-- Creating table 'HOCKY'
CREATE TABLE [dbo].[HOCKY] (
    [HK_MA] varchar(200)  NOT NULL,
    [HK_TEN] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'KHENTHUONGCB'
CREATE TABLE [dbo].[KHENTHUONGCB] (
    [KTCB_MA] varchar(200)  NOT NULL,
    [KTCB_NGAY] nvarchar(max)  NOT NULL,
    [KTCB_THANHTICH] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'KYLUATCB'
CREATE TABLE [dbo].[KYLUATCB] (
    [KLCB_MA] varchar(200)  NOT NULL,
    [KLCB_NGAY] nvarchar(max)  NOT NULL,
    [KLCB_HT] nvarchar(max)  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [CTDG_MA] in table 'CHITIETDANHGIA'
ALTER TABLE [dbo].[CHITIETDANHGIA]
ADD CONSTRAINT [PK_CHITIETDANHGIA]
    PRIMARY KEY CLUSTERED ([CTDG_MA] ASC);
GO

-- Creating primary key on [KT_MA] in table 'KHENTHUONG'
ALTER TABLE [dbo].[KHENTHUONG]
ADD CONSTRAINT [PK_KHENTHUONG]
    PRIMARY KEY CLUSTERED ([KT_MA] ASC);
GO

-- Creating primary key on [KHOI_MA] in table 'KHOI'
ALTER TABLE [dbo].[KHOI]
ADD CONSTRAINT [PK_KHOI]
    PRIMARY KEY CLUSTERED ([KHOI_MA] ASC);
GO

-- Creating primary key on [KL_MA] in table 'KYLUAT'
ALTER TABLE [dbo].[KYLUAT]
ADD CONSTRAINT [PK_KYLUAT]
    PRIMARY KEY CLUSTERED ([KL_MA] ASC);
GO

-- Creating primary key on [LOP_MA] in table 'LOP'
ALTER TABLE [dbo].[LOP]
ADD CONSTRAINT [PK_LOP]
    PRIMARY KEY CLUSTERED ([LOP_MA] ASC);
GO

-- Creating primary key on [NH_MA] in table 'NAMHOC'
ALTER TABLE [dbo].[NAMHOC]
ADD CONSTRAINT [PK_NAMHOC]
    PRIMARY KEY CLUSTERED ([NH_MA] ASC);
GO

-- Creating primary key on [TKB_MA] in table 'THOIKHOABIEU'
ALTER TABLE [dbo].[THOIKHOABIEU]
ADD CONSTRAINT [PK_THOIKHOABIEU]
    PRIMARY KEY CLUSTERED ([TKB_MA] ASC);
GO

-- Creating primary key on [Id] in table 'UpdateImages'
ALTER TABLE [dbo].[UpdateImages]
ADD CONSTRAINT [PK_UpdateImages]
    PRIMARY KEY CLUSTERED ([Id] ASC);
GO

-- Creating primary key on [BL_MA] in table 'BACLUONG'
ALTER TABLE [dbo].[BACLUONG]
ADD CONSTRAINT [PK_BACLUONG]
    PRIMARY KEY CLUSTERED ([BL_MA] ASC);
GO

-- Creating primary key on [CB_MA] in table 'CANBO'
ALTER TABLE [dbo].[CANBO]
ADD CONSTRAINT [PK_CANBO]
    PRIMARY KEY CLUSTERED ([CB_MA] ASC);
GO

-- Creating primary key on [CV_MA] in table 'CHUCVU'
ALTER TABLE [dbo].[CHUCVU]
ADD CONSTRAINT [PK_CHUCVU]
    PRIMARY KEY CLUSTERED ([CV_MA] ASC);
GO

-- Creating primary key on [CN_MA] in table 'CHUYENNGANH'
ALTER TABLE [dbo].[CHUYENNGANH]
ADD CONSTRAINT [PK_CHUYENNGANH]
    PRIMARY KEY CLUSTERED ([CN_MA] ASC);
GO

-- Creating primary key on [CQ_MA] in table 'COQUAN'
ALTER TABLE [dbo].[COQUAN]
ADD CONSTRAINT [PK_COQUAN]
    PRIMARY KEY CLUSTERED ([CQ_MA] ASC);
GO

-- Creating primary key on [CSVC_MA] in table 'COSOVATCHAT'
ALTER TABLE [dbo].[COSOVATCHAT]
ADD CONSTRAINT [PK_COSOVATCHAT]
    PRIMARY KEY CLUSTERED ([CSVC_MA] ASC);
GO

-- Creating primary key on [DT_MA] in table 'DANTOC'
ALTER TABLE [dbo].[DANTOC]
ADD CONSTRAINT [PK_DANTOC]
    PRIMARY KEY CLUSTERED ([DT_MA] ASC);
GO

-- Creating primary key on [HT_MA] in table 'HINHTHUC'
ALTER TABLE [dbo].[HINHTHUC]
ADD CONSTRAINT [PK_HINHTHUC]
    PRIMARY KEY CLUSTERED ([HT_MA] ASC);
GO

-- Creating primary key on [HS_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [PK_HOCSINH]
    PRIMARY KEY CLUSTERED ([HS_MA] ASC);
GO

-- Creating primary key on [MH_MA] in table 'MONHOC'
ALTER TABLE [dbo].[MONHOC]
ADD CONSTRAINT [PK_MONHOC]
    PRIMARY KEY CLUSTERED ([MH_MA] ASC);
GO

-- Creating primary key on [NL_MA] in table 'NGACHLUONG'
ALTER TABLE [dbo].[NGACHLUONG]
ADD CONSTRAINT [PK_NGACHLUONG]
    PRIMARY KEY CLUSTERED ([NL_MA] ASC);
GO

-- Creating primary key on [PH_MA] in table 'PHONGHOC'
ALTER TABLE [dbo].[PHONGHOC]
ADD CONSTRAINT [PK_PHONGHOC]
    PRIMARY KEY CLUSTERED ([PH_MA] ASC);
GO

-- Creating primary key on [QH_MA] in table 'QUANHUYEN'
ALTER TABLE [dbo].[QUANHUYEN]
ADD CONSTRAINT [PK_QUANHUYEN]
    PRIMARY KEY CLUSTERED ([QH_MA] ASC);
GO

-- Creating primary key on [SDG_MA] in table 'SODANHGIA'
ALTER TABLE [dbo].[SODANHGIA]
ADD CONSTRAINT [PK_SODANHGIA]
    PRIMARY KEY CLUSTERED ([SDG_MA] ASC);
GO

-- Creating primary key on [TBDH_MA] in table 'THIETBIDAYHOC'
ALTER TABLE [dbo].[THIETBIDAYHOC]
ADD CONSTRAINT [PK_THIETBIDAYHOC]
    PRIMARY KEY CLUSTERED ([TBDH_MA] ASC);
GO

-- Creating primary key on [TBGD_MA] in table 'THIETBIGIANGDAY'
ALTER TABLE [dbo].[THIETBIGIANGDAY]
ADD CONSTRAINT [PK_THIETBIGIANGDAY]
    PRIMARY KEY CLUSTERED ([TBGD_MA] ASC);
GO

-- Creating primary key on [TTDT_MA] in table 'THONGTINDAOTAO'
ALTER TABLE [dbo].[THONGTINDAOTAO]
ADD CONSTRAINT [PK_THONGTINDAOTAO]
    PRIMARY KEY CLUSTERED ([TTDT_MA] ASC);
GO

-- Creating primary key on [TTL_MA] in table 'THONGTINLUONG'
ALTER TABLE [dbo].[THONGTINLUONG]
ADD CONSTRAINT [PK_THONGTINLUONG]
    PRIMARY KEY CLUSTERED ([TTL_MA] ASC);
GO

-- Creating primary key on [THU_MA] in table 'THU'
ALTER TABLE [dbo].[THU]
ADD CONSTRAINT [PK_THU]
    PRIMARY KEY CLUSTERED ([THU_MA] ASC);
GO

-- Creating primary key on [TH_MA] in table 'TIETHOC'
ALTER TABLE [dbo].[TIETHOC]
ADD CONSTRAINT [PK_TIETHOC]
    PRIMARY KEY CLUSTERED ([TH_MA] ASC);
GO

-- Creating primary key on [TT_MA] in table 'TINHTHANH'
ALTER TABLE [dbo].[TINHTHANH]
ADD CONSTRAINT [PK_TINHTHANH]
    PRIMARY KEY CLUSTERED ([TT_MA] ASC);
GO

-- Creating primary key on [TT_MA] in table 'TINHTRANG'
ALTER TABLE [dbo].[TINHTRANG]
ADD CONSTRAINT [PK_TINHTRANG]
    PRIMARY KEY CLUSTERED ([TT_MA] ASC);
GO

-- Creating primary key on [VB_MA] in table 'VANBANG'
ALTER TABLE [dbo].[VANBANG]
ADD CONSTRAINT [PK_VANBANG]
    PRIMARY KEY CLUSTERED ([VB_MA] ASC);
GO

-- Creating primary key on [XP_MA] in table 'XAPHUONG'
ALTER TABLE [dbo].[XAPHUONG]
ADD CONSTRAINT [PK_XAPHUONG]
    PRIMARY KEY CLUSTERED ([XP_MA] ASC);
GO

-- Creating primary key on [CT_CV_ID] in table 'CHITIET_CHUCVU'
ALTER TABLE [dbo].[CHITIET_CHUCVU]
ADD CONSTRAINT [PK_CHITIET_CHUCVU]
    PRIMARY KEY CLUSTERED ([CT_CV_ID] ASC);
GO

-- Creating primary key on [HK_MA] in table 'HOCKY'
ALTER TABLE [dbo].[HOCKY]
ADD CONSTRAINT [PK_HOCKY]
    PRIMARY KEY CLUSTERED ([HK_MA] ASC);
GO

-- Creating primary key on [KTCB_MA] in table 'KHENTHUONGCB'
ALTER TABLE [dbo].[KHENTHUONGCB]
ADD CONSTRAINT [PK_KHENTHUONGCB]
    PRIMARY KEY CLUSTERED ([KTCB_MA] ASC);
GO

-- Creating primary key on [KLCB_MA] in table 'KYLUATCB'
ALTER TABLE [dbo].[KYLUATCB]
ADD CONSTRAINT [PK_KYLUATCB]
    PRIMARY KEY CLUSTERED ([KLCB_MA] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [SODANHGIA_SDG_MA] in table 'CHITIETDANHGIA'
ALTER TABLE [dbo].[CHITIETDANHGIA]
ADD CONSTRAINT [FK_SODANHGIACHITIETDANHGIA]
    FOREIGN KEY ([SODANHGIA_SDG_MA])
    REFERENCES [dbo].[SODANHGIA]
        ([SDG_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SODANHGIACHITIETDANHGIA'
CREATE INDEX [IX_FK_SODANHGIACHITIETDANHGIA]
ON [dbo].[CHITIETDANHGIA]
    ([SODANHGIA_SDG_MA]);
GO

-- Creating foreign key on [PHONGHOC_PH_MA] in table 'COSOVATCHAT'
ALTER TABLE [dbo].[COSOVATCHAT]
ADD CONSTRAINT [FK_PHONGHOCCOSOVATCHAT]
    FOREIGN KEY ([PHONGHOC_PH_MA])
    REFERENCES [dbo].[PHONGHOC]
        ([PH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PHONGHOCCOSOVATCHAT'
CREATE INDEX [IX_FK_PHONGHOCCOSOVATCHAT]
ON [dbo].[COSOVATCHAT]
    ([PHONGHOC_PH_MA]);
GO

-- Creating foreign key on [BACLUONG_BL_MA] in table 'THONGTINLUONG'
ALTER TABLE [dbo].[THONGTINLUONG]
ADD CONSTRAINT [FK_BACLUONGTHONGTINLUONG]
    FOREIGN KEY ([BACLUONG_BL_MA])
    REFERENCES [dbo].[BACLUONG]
        ([BL_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BACLUONGTHONGTINLUONG'
CREATE INDEX [IX_FK_BACLUONGTHONGTINLUONG]
ON [dbo].[THONGTINLUONG]
    ([BACLUONG_BL_MA]);
GO

-- Creating foreign key on [NGACHLUONG_NL_MA] in table 'THONGTINLUONG'
ALTER TABLE [dbo].[THONGTINLUONG]
ADD CONSTRAINT [FK_NGACHLUONGTHONGTINLUONG]
    FOREIGN KEY ([NGACHLUONG_NL_MA])
    REFERENCES [dbo].[NGACHLUONG]
        ([NL_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_NGACHLUONGTHONGTINLUONG'
CREATE INDEX [IX_FK_NGACHLUONGTHONGTINLUONG]
ON [dbo].[THONGTINLUONG]
    ([NGACHLUONG_NL_MA]);
GO

-- Creating foreign key on [LOP_LOP_MA] in table 'THOIKHOABIEU'
ALTER TABLE [dbo].[THOIKHOABIEU]
ADD CONSTRAINT [FK_LOPTHOIKHOABIEU]
    FOREIGN KEY ([LOP_LOP_MA])
    REFERENCES [dbo].[LOP]
        ([LOP_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LOPTHOIKHOABIEU'
CREATE INDEX [IX_FK_LOPTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEU]
    ([LOP_LOP_MA]);
GO

-- Creating foreign key on [HINHTHUCs_HT_MA] in table 'THONGTINDAOTAO'
ALTER TABLE [dbo].[THONGTINDAOTAO]
ADD CONSTRAINT [FK_THONGTINDAOTAOHINHTHUC]
    FOREIGN KEY ([HINHTHUCs_HT_MA])
    REFERENCES [dbo].[HINHTHUC]
        ([HT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THONGTINDAOTAOHINHTHUC'
CREATE INDEX [IX_FK_THONGTINDAOTAOHINHTHUC]
ON [dbo].[THONGTINDAOTAO]
    ([HINHTHUCs_HT_MA]);
GO

-- Creating foreign key on [CHUCVU_CV_MA] in table 'CHITIET_CHUCVU'
ALTER TABLE [dbo].[CHITIET_CHUCVU]
ADD CONSTRAINT [FK_CHUCVUCHITIET_CHUCVU]
    FOREIGN KEY ([CHUCVU_CV_MA])
    REFERENCES [dbo].[CHUCVU]
        ([CV_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CHUCVUCHITIET_CHUCVU'
CREATE INDEX [IX_FK_CHUCVUCHITIET_CHUCVU]
ON [dbo].[CHITIET_CHUCVU]
    ([CHUCVU_CV_MA]);
GO

-- Creating foreign key on [MONHOC_MH_MA] in table 'THOIKHOABIEU'
ALTER TABLE [dbo].[THOIKHOABIEU]
ADD CONSTRAINT [FK_MONHOCTHOIKHOABIEU]
    FOREIGN KEY ([MONHOC_MH_MA])
    REFERENCES [dbo].[MONHOC]
        ([MH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MONHOCTHOIKHOABIEU'
CREATE INDEX [IX_FK_MONHOCTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEU]
    ([MONHOC_MH_MA]);
GO

-- Creating foreign key on [CHUYENNGANH_CN_MA] in table 'THONGTINDAOTAO'
ALTER TABLE [dbo].[THONGTINDAOTAO]
ADD CONSTRAINT [FK_CHUYENNGANHTHONGTINDAOTAO]
    FOREIGN KEY ([CHUYENNGANH_CN_MA])
    REFERENCES [dbo].[CHUYENNGANH]
        ([CN_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CHUYENNGANHTHONGTINDAOTAO'
CREATE INDEX [IX_FK_CHUYENNGANHTHONGTINDAOTAO]
ON [dbo].[THONGTINDAOTAO]
    ([CHUYENNGANH_CN_MA]);
GO

-- Creating foreign key on [THU_THU_MA] in table 'THOIKHOABIEU'
ALTER TABLE [dbo].[THOIKHOABIEU]
ADD CONSTRAINT [FK_THUTHOIKHOABIEU]
    FOREIGN KEY ([THU_THU_MA])
    REFERENCES [dbo].[THU]
        ([THU_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THUTHOIKHOABIEU'
CREATE INDEX [IX_FK_THUTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEU]
    ([THU_THU_MA]);
GO

-- Creating foreign key on [TIETHOC_TH_MA] in table 'THOIKHOABIEU'
ALTER TABLE [dbo].[THOIKHOABIEU]
ADD CONSTRAINT [FK_TIETHOCTHOIKHOABIEU]
    FOREIGN KEY ([TIETHOC_TH_MA])
    REFERENCES [dbo].[TIETHOC]
        ([TH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TIETHOCTHOIKHOABIEU'
CREATE INDEX [IX_FK_TIETHOCTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEU]
    ([TIETHOC_TH_MA]);
GO

-- Creating foreign key on [VANBANG_VB_MA] in table 'THONGTINDAOTAO'
ALTER TABLE [dbo].[THONGTINDAOTAO]
ADD CONSTRAINT [FK_VANBANGTHONGTINDAOTAO]
    FOREIGN KEY ([VANBANG_VB_MA])
    REFERENCES [dbo].[VANBANG]
        ([VB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VANBANGTHONGTINDAOTAO'
CREATE INDEX [IX_FK_VANBANGTHONGTINDAOTAO]
ON [dbo].[THONGTINDAOTAO]
    ([VANBANG_VB_MA]);
GO

-- Creating foreign key on [THIETBIGIANGDAY_TBGD_MA] in table 'COSOVATCHAT'
ALTER TABLE [dbo].[COSOVATCHAT]
ADD CONSTRAINT [FK_THIETBIGIANGDAYCOSOVATCHAT]
    FOREIGN KEY ([THIETBIGIANGDAY_TBGD_MA])
    REFERENCES [dbo].[THIETBIGIANGDAY]
        ([TBGD_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THIETBIGIANGDAYCOSOVATCHAT'
CREATE INDEX [IX_FK_THIETBIGIANGDAYCOSOVATCHAT]
ON [dbo].[COSOVATCHAT]
    ([THIETBIGIANGDAY_TBGD_MA]);
GO

-- Creating foreign key on [THIETBIDAYHOC_TBDH_MA] in table 'COSOVATCHAT'
ALTER TABLE [dbo].[COSOVATCHAT]
ADD CONSTRAINT [FK_THIETBIDAYHOCCOSOVATCHAT]
    FOREIGN KEY ([THIETBIDAYHOC_TBDH_MA])
    REFERENCES [dbo].[THIETBIDAYHOC]
        ([TBDH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THIETBIDAYHOCCOSOVATCHAT'
CREATE INDEX [IX_FK_THIETBIDAYHOCCOSOVATCHAT]
ON [dbo].[COSOVATCHAT]
    ([THIETBIDAYHOC_TBDH_MA]);
GO

-- Creating foreign key on [TINHTRANG_TT_MA] in table 'COSOVATCHAT'
ALTER TABLE [dbo].[COSOVATCHAT]
ADD CONSTRAINT [FK_TINHTRANGCOSOVATCHAT]
    FOREIGN KEY ([TINHTRANG_TT_MA])
    REFERENCES [dbo].[TINHTRANG]
        ([TT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TINHTRANGCOSOVATCHAT'
CREATE INDEX [IX_FK_TINHTRANGCOSOVATCHAT]
ON [dbo].[COSOVATCHAT]
    ([TINHTRANG_TT_MA]);
GO

-- Creating foreign key on [TINHTHANH_TT_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_TINHTHANHHOCSINH]
    FOREIGN KEY ([TINHTHANH_TT_MA])
    REFERENCES [dbo].[TINHTHANH]
        ([TT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TINHTHANHHOCSINH'
CREATE INDEX [IX_FK_TINHTHANHHOCSINH]
ON [dbo].[HOCSINH]
    ([TINHTHANH_TT_MA]);
GO

-- Creating foreign key on [XAPHUONG_XP_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_XAPHUONGHOCSINH]
    FOREIGN KEY ([XAPHUONG_XP_MA])
    REFERENCES [dbo].[XAPHUONG]
        ([XP_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_XAPHUONGHOCSINH'
CREATE INDEX [IX_FK_XAPHUONGHOCSINH]
ON [dbo].[HOCSINH]
    ([XAPHUONG_XP_MA]);
GO

-- Creating foreign key on [KYLUAT_KL_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_KYLUATHOCSINH]
    FOREIGN KEY ([KYLUAT_KL_MA])
    REFERENCES [dbo].[KYLUAT]
        ([KL_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KYLUATHOCSINH'
CREATE INDEX [IX_FK_KYLUATHOCSINH]
ON [dbo].[HOCSINH]
    ([KYLUAT_KL_MA]);
GO

-- Creating foreign key on [KHENTHUONG_KT_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_KHENTHUONGHOCSINH]
    FOREIGN KEY ([KHENTHUONG_KT_MA])
    REFERENCES [dbo].[KHENTHUONG]
        ([KT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KHENTHUONGHOCSINH'
CREATE INDEX [IX_FK_KHENTHUONGHOCSINH]
ON [dbo].[HOCSINH]
    ([KHENTHUONG_KT_MA]);
GO

-- Creating foreign key on [CHITIETDANHGIA_CTDG_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_CHITIETDANHGIAHOCSINH]
    FOREIGN KEY ([CHITIETDANHGIA_CTDG_MA])
    REFERENCES [dbo].[CHITIETDANHGIA]
        ([CTDG_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CHITIETDANHGIAHOCSINH'
CREATE INDEX [IX_FK_CHITIETDANHGIAHOCSINH]
ON [dbo].[HOCSINH]
    ([CHITIETDANHGIA_CTDG_MA]);
GO

-- Creating foreign key on [QUANHUYEN_QH_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_QUANHUYENHOCSINH]
    FOREIGN KEY ([QUANHUYEN_QH_MA])
    REFERENCES [dbo].[QUANHUYEN]
        ([QH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_QUANHUYENHOCSINH'
CREATE INDEX [IX_FK_QUANHUYENHOCSINH]
ON [dbo].[HOCSINH]
    ([QUANHUYEN_QH_MA]);
GO

-- Creating foreign key on [DANTOC_DT_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_DANTOCHOCSINH]
    FOREIGN KEY ([DANTOC_DT_MA])
    REFERENCES [dbo].[DANTOC]
        ([DT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DANTOCHOCSINH'
CREATE INDEX [IX_FK_DANTOCHOCSINH]
ON [dbo].[HOCSINH]
    ([DANTOC_DT_MA]);
GO

-- Creating foreign key on [LOP_LOP_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_LOPHOCSINH]
    FOREIGN KEY ([LOP_LOP_MA])
    REFERENCES [dbo].[LOP]
        ([LOP_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LOPHOCSINH'
CREATE INDEX [IX_FK_LOPHOCSINH]
ON [dbo].[HOCSINH]
    ([LOP_LOP_MA]);
GO

-- Creating foreign key on [COQUAN_CQ_MA] in table 'CANBO'
ALTER TABLE [dbo].[CANBO]
ADD CONSTRAINT [FK_COQUANCANBO]
    FOREIGN KEY ([COQUAN_CQ_MA])
    REFERENCES [dbo].[COQUAN]
        ([CQ_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COQUANCANBO'
CREATE INDEX [IX_FK_COQUANCANBO]
ON [dbo].[CANBO]
    ([COQUAN_CQ_MA]);
GO

-- Creating foreign key on [CHITIET_CHUCVU_CT_CV_ID] in table 'CANBO'
ALTER TABLE [dbo].[CANBO]
ADD CONSTRAINT [FK_CHITIET_CHUCVUCANBO]
    FOREIGN KEY ([CHITIET_CHUCVU_CT_CV_ID])
    REFERENCES [dbo].[CHITIET_CHUCVU]
        ([CT_CV_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CHITIET_CHUCVUCANBO'
CREATE INDEX [IX_FK_CHITIET_CHUCVUCANBO]
ON [dbo].[CANBO]
    ([CHITIET_CHUCVU_CT_CV_ID]);
GO

-- Creating foreign key on [KYLUATCB_KLCB_MA] in table 'CANBO'
ALTER TABLE [dbo].[CANBO]
ADD CONSTRAINT [FK_KYLUATCBCANBO]
    FOREIGN KEY ([KYLUATCB_KLCB_MA])
    REFERENCES [dbo].[KYLUATCB]
        ([KLCB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KYLUATCBCANBO'
CREATE INDEX [IX_FK_KYLUATCBCANBO]
ON [dbo].[CANBO]
    ([KYLUATCB_KLCB_MA]);
GO

-- Creating foreign key on [KHENTHUONGCB_KTCB_MA] in table 'CANBO'
ALTER TABLE [dbo].[CANBO]
ADD CONSTRAINT [FK_KHENTHUONGCBCANBO]
    FOREIGN KEY ([KHENTHUONGCB_KTCB_MA])
    REFERENCES [dbo].[KHENTHUONGCB]
        ([KTCB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KHENTHUONGCBCANBO'
CREATE INDEX [IX_FK_KHENTHUONGCBCANBO]
ON [dbo].[CANBO]
    ([KHENTHUONGCB_KTCB_MA]);
GO

-- Creating foreign key on [CANBO_CB_MA] in table 'THOIKHOABIEU'
ALTER TABLE [dbo].[THOIKHOABIEU]
ADD CONSTRAINT [FK_CANBOTHOIKHOABIEU]
    FOREIGN KEY ([CANBO_CB_MA])
    REFERENCES [dbo].[CANBO]
        ([CB_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CANBOTHOIKHOABIEU'
CREATE INDEX [IX_FK_CANBOTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEU]
    ([CANBO_CB_MA]);
GO

-- Creating foreign key on [THONGTINDAOTAO_TTDT_MA] in table 'CANBO'
ALTER TABLE [dbo].[CANBO]
ADD CONSTRAINT [FK_THONGTINDAOTAOCANBO]
    FOREIGN KEY ([THONGTINDAOTAO_TTDT_MA])
    REFERENCES [dbo].[THONGTINDAOTAO]
        ([TTDT_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THONGTINDAOTAOCANBO'
CREATE INDEX [IX_FK_THONGTINDAOTAOCANBO]
ON [dbo].[CANBO]
    ([THONGTINDAOTAO_TTDT_MA]);
GO

-- Creating foreign key on [HOCKY_HK_MA] in table 'THOIKHOABIEU'
ALTER TABLE [dbo].[THOIKHOABIEU]
ADD CONSTRAINT [FK_HOCKYTHOIKHOABIEU]
    FOREIGN KEY ([HOCKY_HK_MA])
    REFERENCES [dbo].[HOCKY]
        ([HK_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_HOCKYTHOIKHOABIEU'
CREATE INDEX [IX_FK_HOCKYTHOIKHOABIEU]
ON [dbo].[THOIKHOABIEU]
    ([HOCKY_HK_MA]);
GO

-- Creating foreign key on [KHOI_KHOI_MA] in table 'HOCSINH'
ALTER TABLE [dbo].[HOCSINH]
ADD CONSTRAINT [FK_KHOIHOCSINH]
    FOREIGN KEY ([KHOI_KHOI_MA])
    REFERENCES [dbo].[KHOI]
        ([KHOI_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_KHOIHOCSINH'
CREATE INDEX [IX_FK_KHOIHOCSINH]
ON [dbo].[HOCSINH]
    ([KHOI_KHOI_MA]);
GO

-- Creating foreign key on [THONGTINLUONG_TTL_MA] in table 'CANBO'
ALTER TABLE [dbo].[CANBO]
ADD CONSTRAINT [FK_THONGTINLUONGCANBO]
    FOREIGN KEY ([THONGTINLUONG_TTL_MA])
    REFERENCES [dbo].[THONGTINLUONG]
        ([TTL_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_THONGTINLUONGCANBO'
CREATE INDEX [IX_FK_THONGTINLUONGCANBO]
ON [dbo].[CANBO]
    ([THONGTINLUONG_TTL_MA]);
GO

-- Creating foreign key on [NAMHOC_NH_MA] in table 'SODANHGIA'
ALTER TABLE [dbo].[SODANHGIA]
ADD CONSTRAINT [FK_NAMHOCSODANHGIA]
    FOREIGN KEY ([NAMHOC_NH_MA])
    REFERENCES [dbo].[NAMHOC]
        ([NH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_NAMHOCSODANHGIA'
CREATE INDEX [IX_FK_NAMHOCSODANHGIA]
ON [dbo].[SODANHGIA]
    ([NAMHOC_NH_MA]);
GO

-- Creating foreign key on [MONHOC_MH_MA] in table 'CHITIETDANHGIA'
ALTER TABLE [dbo].[CHITIETDANHGIA]
ADD CONSTRAINT [FK_MONHOCCHITIETDANHGIA]
    FOREIGN KEY ([MONHOC_MH_MA])
    REFERENCES [dbo].[MONHOC]
        ([MH_MA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MONHOCCHITIETDANHGIA'
CREATE INDEX [IX_FK_MONHOCCHITIETDANHGIA]
ON [dbo].[CHITIETDANHGIA]
    ([MONHOC_MH_MA]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------