//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAMHOC
    {
        public NAMHOC()
        {
            this.LOPs = new HashSet<LOP>();
        }
    
        public string NH_MA { get; set; }
        public string NH_NAMHOC { get; set; }
    
        public virtual ICollection<LOP> LOPs { get; set; }
    }
}
