//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODANHGIA
    {
        public SODANHGIA()
        {
            this.HOCSINHs = new HashSet<HOCSINH>();
        }
    
        public string SDG_MA { get; set; }
        public string SDG_DIEM { get; set; }
        public string SDG_GHICHU { get; set; }
        public string MH_MA { get; set; }
        public string HOCKYHK_MA { get; set; }
    
        public virtual HOCKy HOCKy { get; set; }
        public virtual ICollection<HOCSINH> HOCSINHs { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
