//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIKHOABIEU
    {
        public string TKB_MA { get; set; }
        public string CB_MA { get; set; }
        public string MH_MA { get; set; }
        public string THU_MA { get; set; }
        public string TH_MA { get; set; }
    
        public virtual CANBO CANBO { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual TIETHOC TIETHOC { get; set; }
        public virtual THU THU { get; set; }
    }
}
