//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINDAOTAO
    {
        public string TTDT_MA { get; set; }
        public string CN_MA { get; set; }
        public string VB_MA { get; set; }
        public string CB_MA { get; set; }
        public string HT_MA { get; set; }
    
        public virtual CANBO CANBO { get; set; }
        public virtual CHUYENNGANH CHUYENNGANH { get; set; }
        public virtual HINHTHUC HINHTHUC { get; set; }
        public virtual VANBANG VANBANG { get; set; }
    }
}
