//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAMHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAMHOC()
        {
<<<<<<< HEAD:QLTHPT/Models/NAMHOC.cs
=======
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
>>>>>>> ef4a19d4ecc2602c2d63d0bc2587774ef2fc4dcd:Models/NAMHOC.cs
            this.SODANHGIAs = new HashSet<SODANHGIA>();
        }
    
        public string NH_MA { get; set; }
        public string NH_NAMHOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD:QLTHPT/Models/NAMHOC.cs
=======
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
>>>>>>> ef4a19d4ecc2602c2d63d0bc2587774ef2fc4dcd:Models/NAMHOC.cs
        public virtual ICollection<SODANHGIA> SODANHGIAs { get; set; }
    }
}
