//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINLUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINLUONG()
        {
            this.CANBOes = new HashSet<CANBO>();
        }
    
        public string TTL_MA { get; set; }
        public string TTL_NGAYNHANLUONG { get; set; }
        public string TTL_HESOLUONG { get; set; }
        public string BACLUONG_BL_MA { get; set; }
        public string NGACHLUONG_NL_MA { get; set; }
    
        public virtual BACLUONG BACLUONG { get; set; }
        public virtual NGACHLUONG NGACHLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANBO> CANBOes { get; set; }
    }
}
